### ISSUE TITLE
Flaky execution of workers

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#1027]
@hansl observed some failures on circleci that were fixed by re-running:

https://circleci.com/gh/angular/devkit/8171#build-timing 
https://circleci.com/gh/angular/devkit/8234
```
[40 / 47] Compiling TypeScript (devmode) //packages/angular_devkit/core:spec; 23s worker ... (3 actions running)

ERROR: /home/circleci/ng/packages/angular_devkit/schematics/BUILD:86:1: Compiling TypeScript (devmode) //packages/angular_devkit/schematics:spec failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at /home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/bazel-workers/worker-1-TypeScriptCompile.log ---8<---8<---
Starting TypeScript compiler persistent worker...
---8<---8<--- End of log ---8<---8<---

INFO: Elapsed time: 107.947s, Critical Path: 61.69s

FAILED: Build did NOT complete successfully
```

https://circleci.com/gh/angular/devkit/8274
```
[40 / 47] Compiling TypeScript (devmode) //packages/angular_devkit/core:spec; 2s worker ... (2 actions, 1 running)

ERROR: /home/circleci/ng/packages/angular_devkit/schematics_cli/BUILD:11:1: Compiling TypeScript (devmode) //packages/angular_devkit/schematics_cli:schematics-cli failed: Worker process quit or closed its stdin stream when we tried to send a WorkRequest:

---8<---8<--- Exception details ---8<---8<---
java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.doFlush(CodedOutputStream.java:2985)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.write(CodedOutputStream.java:2917)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeLazy(CodedOutputStream.java:2936)
	at com.google.protobuf.ByteString$LiteralByteString.writeTo(ByteString.java:1337)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytesNoTag(CodedOutputStream.java:2735)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytes(CodedOutputStream.java:2708)
	at com.google.protobuf.GeneratedMessageV3.writeString(GeneratedMessageV3.java:2716)
	at com.google.devtools.build.lib.worker.WorkerProtocol$Input.writeTo(WorkerProtocol.java:214)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessageNoTag(CodedOutputStream.java:2783)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessage(CodedOutputStream.java:2759)
	at com.google.devtools.build.lib.worker.WorkerProtocol$WorkRequest.writeTo(WorkerProtocol.java:975)
	at com.google.protobuf.AbstractMessageLite.writeDelimitedTo(AbstractMessageLite.java:98)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.execInWorker(WorkerSpawnRunner.java:284)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.actuallyExec(WorkerSpawnRunner.java:156)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.exec(WorkerSpawnRunner.java:111)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:97)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:65)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:266)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:273)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:860)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:803)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:110)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:671)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:628)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:412)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:444)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:201)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
---8<---8<--- End of exception details ---8<---8<---

---8<---8<--- Start of log, file at /home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/bazel-workers/worker-0-TypeScriptCompile.log ---8<---8<---
Starting TypeScript compiler persistent worker...
---8<---8<--- End of log ---8<---8<---

INFO: Elapsed time: 80.366s, Critical Path: 29.23s

FAILED: Build did NOT complete successfully
```

**Comment by marcus-sa** [comment]
This happened to me as well when I manually ran `$ killall node`

**Comment by sonukapoor** [comment]
I am receiving the same error locally every time when I run `yarn bazel test //packages/service-worker/test`. This is for the angular repo as well. I am on Windows 10, have developer mode enabled and use PowerShell to run the command in the root of the repo. I also had to set the `--output_user_root` because `bazel` was complaining about space in my `HOME` directory. Here is the error I see: 

```
$ bazel --output_user_root=C:\bazel-temp1\ test //packages/service-worker/test
Starting local Bazel server and connecting to it...
INFO: Analyzed target //packages/service-worker/test:test (231 packages loaded, 9356 targets configured).
INFO: Found 1 test target...
INFO: Deleting stale sandbox base C:/bazel-temp1/7lxopdvs/sandbox
ERROR: C:/projects/archive/angular/packages/compiler-cli/src/ngtsc/core/BUILD.bazel:40:1: Compiling TypeScript (devmode) //packages/compiler-cli/src/ngtsc/core:api failed: Worker process quit or closed its stdin stream when we tried to send a WorkRequest:

---8<---8<--- Exception details ---8<---8<---
java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(356): NativeProcess:WriteStdin(14356): The pipe is being closed.

        at com.google.devtools.build.lib.windows.WindowsSubprocess.writeStream(WindowsSubprocess.java:263)
        at com.google.devtools.build.lib.windows.WindowsSubprocess.access$000(WindowsSubprocess.java:33)
        at com.google.devtools.build.lib.windows.WindowsSubprocess$ProcessOutputStream.write(WindowsSubprocess.java:57)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.doFlush(CodedOutputStream.java:3003)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.write(CodedOutputStream.java:2935)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeLazy(CodedOutputStream.java:2954)
        at com.google.protobuf.ByteString$LiteralByteString.writeTo(ByteString.java:1331)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytesNoTag(CodedOutputStream.java:2751)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytes(CodedOutputStream.java:2724)
        at com.google.protobuf.GeneratedMessageV3.writeString(GeneratedMessageV3.java:2721)
        at com.google.devtools.build.lib.worker.WorkerProtocol$Input.writeTo(WorkerProtocol.java:220)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessageNoTag(CodedOutputStream.java:2800)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessage(CodedOutputStream.java:2775)
        at com.google.devtools.build.lib.worker.WorkerProtocol$WorkRequest.writeTo(WorkerProtocol.java:1040)
        at com.google.protobuf.AbstractMessageLite.writeDelimitedTo(AbstractMessageLite.java:98)
        at com.google.devtools.build.lib.worker.Worker.putRequest(Worker.java:125)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.execInWorker(WorkerSpawnRunner.java:353)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.actuallyExec(WorkerSpawnRunner.java:190)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.exec(WorkerSpawnRunner.java:129)
        at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:229)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:124)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:89)
        at com.google.devtools.build.lib.actions.SpawnActionContext.beginExecution(SpawnActionContext.java:41)
        at com.google.devtools.build.lib.exec.ProxySpawnActionContext.beginExecution(ProxySpawnActionContext.java:60)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:331)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:124)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:931)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1070)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1041)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:116)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:77)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:608)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:903)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:297)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
---8<---8<--- End of exception details ---8<---8<---

---8<---8<--- Start of log, file at C:/bazel-temp1/7lxopdvs/bazel-workers/worker-1-TypeScriptCompile.log ---8<---8<---
/bin/bash: C:/bazel-temp1/7lxopdvs/execroot/angular/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.sh: No such file or directory
---8<---8<--- End of log ---8<---8<---
Target //packages/service-worker/test:test failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: C:/projects/archive/angular/packages/service-worker/test/BUILD.bazel:26:1 Compiling TypeScript (devmode) //packages/compiler-cli/src/ngtsc/core:api failed: Worker process quit or closed its stdin stream when we tried to send a WorkRequest:

---8<---8<--- Exception details ---8<---8<---
java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(356): NativeProcess:WriteStdin(14356): The pipe is being closed.

        at com.google.devtools.build.lib.windows.WindowsSubprocess.writeStream(WindowsSubprocess.java:263)
        at com.google.devtools.build.lib.windows.WindowsSubprocess.access$000(WindowsSubprocess.java:33)
        at com.google.devtools.build.lib.windows.WindowsSubprocess$ProcessOutputStream.write(WindowsSubprocess.java:57)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.doFlush(CodedOutputStream.java:3003)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.write(CodedOutputStream.java:2935)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeLazy(CodedOutputStream.java:2954)
        at com.google.protobuf.ByteString$LiteralByteString.writeTo(ByteString.java:1331)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytesNoTag(CodedOutputStream.java:2751)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytes(CodedOutputStream.java:2724)
        at com.google.protobuf.GeneratedMessageV3.writeString(GeneratedMessageV3.java:2721)
        at com.google.devtools.build.lib.worker.WorkerProtocol$Input.writeTo(WorkerProtocol.java:220)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessageNoTag(CodedOutputStream.java:2800)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessage(CodedOutputStream.java:2775)
        at com.google.devtools.build.lib.worker.WorkerProtocol$WorkRequest.writeTo(WorkerProtocol.java:1040)
        at com.google.protobuf.AbstractMessageLite.writeDelimitedTo(AbstractMessageLite.java:98)
        at com.google.devtools.build.lib.worker.Worker.putRequest(Worker.java:125)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.execInWorker(WorkerSpawnRunner.java:353)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.actuallyExec(WorkerSpawnRunner.java:190)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.exec(WorkerSpawnRunner.java:129)
        at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:229)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:124)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:89)
        at com.google.devtools.build.lib.actions.SpawnActionContext.beginExecution(SpawnActionContext.java:41)
        at com.google.devtools.build.lib.exec.ProxySpawnActionContext.beginExecution(ProxySpawnActionContext.java:60)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:331)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:124)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:931)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1070)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1041)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:116)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:77)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:608)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:903)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:297)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
---8<---8<--- End of exception details ---8<---8<---

---8<---8<--- Start of log, file at C:/bazel-temp1/7lxopdvs/bazel-workers/worker-1-TypeScriptCompile.log ---8<---8<---
/bin/bash: C:/bazel-temp1/7lxopdvs/execroot/angular/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.sh: No such file or directory
---8<---8<--- End of log ---8<---8<---
INFO: Elapsed time: 48.566s, Critical Path: 1.13s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
//packages/service-worker/test:test                             FAILED TO BUILD

FAILED: Build did NOT complete successfully
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Anything I can do to fix this?

**Comment by flolu** [comment]
Also getting this error on Google Cloud Build (full log [here](https://00e9e64bac0265af078166688dd1c1e7da4ca6205f9ef7599d-apidata.googleusercontent.com/download/storage/v1/b/535395706340.cloudbuild-logs.googleusercontent.com/o/log-e7beca29-a51b-43ff-9e47-546f0f427f18.txt?qk=AD5uMEuHxuwMd0G6aiLKZPMh5xtQb8zW-kdC-uGV2Z1mynSZ90pX3syRaRj7o7Izn6HwuOQQLV3lmJAdMsczkUd8stRVcyNwGNujKyrynGBhbW6_WWlUL5ZBrldiS_Wt3e4IMhEbxrxkyWGwHhZQLFMRS1n1X5q_9oxjliwWaNX8YCMa0EuoBcwdjVagMUI-9hgPltVnsr8X6w2cofnqVN4CiszsInHnezBkZ3VVXHGTDHYK-EnyJr7a6DwsRnAYEl_3zmZQ6igSclyeFDSdIr0JWrmH2V0qanUd-UInBlbSmx8m7AiqfvmKeckOzrCobrZdWvs-m5VwDgCzGVpZGFezXGWPikfiuKl0bpiBXw_KyvOqF-ssIwgeTxwpCVTe5UrcZKH90dj2XRY8iuVEknYqpuneiOSJz3Iz6TlW6yjQbj8n21ilReu0GMHuK1rdmMx_bcU7m8QfPWZW7rigqCH20sloxBc7W21xG34cZyRACcEZBYj8wyRMmM7yG6M0Bo3J_LknazFVGQzn9gwvDg2dPksrssvX_T1gdvkr_P_n2z_4iTVTmxI1Jjn7KzB_6MaNLXkvia2KpcHVM583PNCq3X5oOF-ODjyTMKIvVqq-SFUqDHd4ZjNZyMEZl6zI2nn5kU4jv8yP2VeFl2zG99PAJ94VObPZ7P5F6zOOWM7ZKchK1E9tgrHSPrYZX9w0Gh5Ath1WtK_Qw10cTyATpJgrAiV8MbUnhJ06fnUvUbVfcvgL_UYSI9k08L2yCXBwxej8WnOr8STczhGCQ7nwQDVBcxZ5YsmOi_R8pWHbBVtNoadoOw7zFs0dFisZuJdcCB4vW5MnoDXwr7ixd81kjpPx2xDsHs1eXtaG1QVO7w98eqSWFIo39hltvqOSfGs_L3iUGhbm7pHV&isca=1))
```
ERROR: /workspace/services/client/src/app/user/BUILD.bazel:37:1: Compiling Angular templates (Ivy - prodmode) //services/client/src/app/user:user failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/bazel-workers/worker-13-AngularTemplateCompile.log ---8<---8<---
(empty)
---8<---8<--- End of log ---8<---8<---
ERROR: /workspace/services/client/src/BUILD.bazel:78:1 Compiling Angular templates (Ivy - prodmode) //services/client/src/app/user:user failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/bazel-workers/worker-13-AngularTemplateCompile.log ---8<---8<---
(empty)
---8<---8<--- End of log ---8<---8<---
```

But it does not happen on my local Ubuntu machine :thinking:
