### ISSUE TITLE
jasmine_node_test args fails after 0.36.0 update

### ISSUE THREAD

**Issue by kellycampbell** [bazelbuild/rules_nodejs#1051]
# 🐞 bug report

### Affected Rule

`jasmine_node_test`

### Is this a regression?

Yes, the previous version in which this bug was not present was: **0.35.0**

### Description

Our `jasmine_node_test` rules started failing with the 0.36.0 release related to `args`. 

## 🔥 Exception or Error

```
==================== Test output for //services/auth/tests/accounts:test:
Error: //services/accounts/tests/accounts:test cannot find module '--test_env' required by '/home/user/.cache/bazel/_bazel_user/cbed9a7d7f782014f5bc28009322fa52/sandbox/linux-sandbox/74/execroot/proj/bazel-out/k8-fastbuild/bin/services/accounts/tests/accounts/test.sh.runfiles/npm/node_modules/@bazel/jasmine/jasmine_runner.js'
  looked in:
    built-in, relative, absolute, nested node_modules - Error: Cannot find module '--test_env'
```

## 🔬 Minimal Reproduction

Our rules are specified like this:

```
jasmine_node_test(
    name = "test",
    size = "medium",
    srcs = [
        ":test_lib"
    ],
    args = [
        "--test_env NODE_ENV=test",
    ],
)
```
where `test_lib` is a `ts_library` containing the test specs.

If I comment out the `args =` section, it gets a different error:

```
==================== Test output for //services/accounts/tests/accounts:test:
Error: expected argument missing
    at main (node_modules/@bazel/jasmine/jasmine_runner.js:64:11)
    at Object.<anonymous> (node_modules/@bazel/jasmine/jasmine_runner.js:221:22)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Object.<anonymous> (services/auth/tests/accounts/test_loader.js:511:24)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10)
    at internal/main/run_main_module.js:17:11
================================================================================
```

## 🌍  Your Environment

**Operating System:**

```
linux, ubuntu 18.04
```

**Output of `bazel version`:**

```
Build label: 0.28.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 19 15:19:51 2019 (1563549591)
Build timestamp: 1563549591
Build timestamp as int: 1563549591
```

**Rules version (SHA):**

0.36.0 `9abd649b74317c9c135f4810636aaa838d5bea4913bfa93a85c2f52a919fdaf3`

**Comment by kellycampbell** [comment]
Others on my team weren't seeing the same problem. Running `bazel clean --expunge` fixed the issue. It isn't fixed without the `--expunge` however.

**Comment by alexeagle** [comment]
I'm guessing the update got a new @bazel/jasmine npm package but the repository_rule to lay out the `@npm_bazel_jasmine` bazel repository wasn't run for some reason. Having the two at different versions should probably just throw immediately.
