### ISSUE TITLE
Tests are flaky

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#1223]
This is an issue to report test flakes observed

**Comment by gregmagolan** [comment]
```================================================================================
==================== Test output for //examples:examples_nestjs:
[test_runner.js] running 'bazel version'
$TEST_TMPDIR defined: output root default is '/private/var/tmp/_bazel_buildkite/3b7376862aa4ff0611676716915686cc/execroot/build_bazel_rules_nodejs/_tmp/0bcdfc70abd9e1e87543e56e37c79228' and max_idle_secs default is '15'.
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Build label: 0.28.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 19 15:22:50 2019 (1563549770)
Build timestamp: 1563549770
Build timestamp as int: 1563549770
[test_runner.js] running 'bazel build ... --local_resources=13288,1.0,1.0 --test_tag_filters=-no-bazelci,-no-bazelci-mac,-manual'
$TEST_TMPDIR defined: output root default is '/private/var/tmp/_bazel_buildkite/3b7376862aa4ff0611676716915686cc/execroot/build_bazel_rules_nodejs/_tmp/0bcdfc70abd9e1e87543e56e37c79228' and max_idle_secs default is '15'.
Loading:
Loading: 0 packages loaded
INFO: SHA256 (file:/private/var/tmp/_bazel_buildkite/3b7376862aa4ff0611676716915686cc/execroot/build_bazel_rules_nodejs/bazel-out/darwin-fastbuild/bin/examples/examples_nestjs.sh.runfiles/build_bazel_rules_nodejs/release.tar.gz) = feb518783ce17b6ce6cc5f171c3de69b5b28a14e13c7dca7d0782dbbbc5ac80e
DEBUG: Rule 'build_bazel_rules_nodejs' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "feb518783ce17b6ce6cc5f171c3de69b5b28a14e13c7dca7d0782dbbbc5ac80e"
DEBUG: Call stack for the definition of repository 'build_bazel_rules_nodejs' which is a http_archive (rule definition at /private/var/tmp/_bazel_buildkite/3b7376862aa4ff0611676716915686cc/execroot/build_bazel_rules_nodejs/_tmp/0bcdfc70abd9e1e87543e56e37c79228/_bazel_buildkite/4e69be88f3d889cf908a79fcb766042f/external/bazel_tools/tools/build_defs/repo/http.bzl:237:16):
 - /private/tmp/tmp-97710zbnKTwwpsLqn/WORKSPACE:23:1
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Analyzing: 6 targets (2 packages loaded, 0 targets configured)
Analyzing: 6 targets (54 packages loaded, 5717 targets configured)
Analyzing: 6 targets (54 packages loaded, 5717 targets configured)
Analyzing: 6 targets (54 packages loaded, 5717 targets configured)
Analyzing: 6 targets (161 packages loaded, 7396 targets configured)
Analyzing: 6 targets (192 packages loaded, 13858 targets configured)
Analyzing: 6 targets (193 packages loaded, 13954 targets configured)
Analyzing: 6 targets (194 packages loaded, 13954 targets configured)
INFO: Analyzed 6 targets (200 packages loaded, 14012 targets configured).
INFO: Found 6 targets...
[0 / 26] [Prepa] Expanding template external/bazel_tools/tools/build_defs/hash/sha256 [for host] ... (9 actions, 0 running)
[36 / 39] [Prepa] SHA256 src/docker-layer.tar.sha256
INFO: Elapsed time: 40.709s, Critical Path: 7.80s
INFO: 8 processes: 7 darwin-sandbox, 1 worker.
INFO: Build completed successfully, 39 total actions
INFO: Build completed successfully, 39 total actions
[test_runner.js] running 'bazel build --platforms=@build_bazel_rules_nodejs//toolchains/node:linux_amd64 //src:docker --local_resources=13288,1.0,1.0 --test_tag_filters=-no-bazelci,-no-bazelci-mac,-manual'
$TEST_TMPDIR defined: output root default is '/private/var/tmp/_bazel_buildkite/3b7376862aa4ff0611676716915686cc/execroot/build_bazel_rules_nodejs/_tmp/0bcdfc70abd9e1e87543e56e37c79228' and max_idle_secs default is '15'.
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
DEBUG: Rule 'build_bazel_rules_nodejs' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "feb518783ce17b6ce6cc5f171c3de69b5b28a14e13c7dca7d0782dbbbc5ac80e"
DEBUG: Call stack for the definition of repository 'build_bazel_rules_nodejs' which is a http_archive (rule definition at /private/var/tmp/_bazel_buildkite/3b7376862aa4ff0611676716915686cc/execroot/build_bazel_rules_nodejs/_tmp/0bcdfc70abd9e1e87543e56e37c79228/_bazel_buildkite/4e69be88f3d889cf908a79fcb766042f/external/bazel_tools/tools/build_defs/repo/http.bzl:237:16):
 - /private/tmp/tmp-97710zbnKTwwpsLqn/WORKSPACE:23:1
INFO: Build option --platforms has changed, discarding analysis cache.
Analyzing: target //src:docker (0 packages loaded, 0 targets configured)
Analyzing: target //src:docker (61 packages loaded, 6784 targets configured)
Analyzing: target //src:docker (68 packages loaded, 6825 targets configured)
Analyzing: target //src:docker (69 packages loaded, 6937 targets configured)
Analyzing: target //src:docker (69 packages loaded, 6937 targets configured)
ERROR: /private/tmp/tmp-97710zbnKTwwpsLqn/src/BUILD.bazel:19:1: no such package '': error globbing [**/*] - [bazel-out/**/*, dist/**/*, node_modules/**/*]: /private/tmp/tmp-97710zbnKTwwpsLqn/bazel-out/darwin-fastbuild/bin/src/server.sh.runfiles/npm/node_modules/reflect-metadata/reflect-metadata.d.ts (Not a directory) and referenced by '//src:app'
ERROR: Analysis of target '//src:docker' failed; build aborted: no such package '': error globbing [**/*] - [bazel-out/**/*, dist/**/*, node_modules/**/*]: /private/tmp/tmp-97710zbnKTwwpsLqn/bazel-out/darwin-fastbuild/bin/src/server.sh.runfiles/npm/node_modules/reflect-metadata/reflect-metadata.d.ts (Not a directory)
INFO: Elapsed time: 7.078s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (199 packages loaded, 6993 targets configured)
FAILED: Build did NOT complete successfully (199 packages loaded, 6993 targets configured)
================================================================================
(23:01:14) [516 / 526] 3 / 10 tests, 1 failed;  1 action; last test: //examples:examples_nestjs
    Testing //examples:examples_nestjs; 0s local```

**Comment by gregmagolan** [comment]
I've only seen this once running locally on OSX.

```
Running e2e test karma_typescript
checking deps: release
all deps built
+ yarn test
yarn run v1.16.0
warning package.json: No license field
$ bazel test ...
Starting local Bazel server and connecting to it...
DEBUG: /private/var/tmp/_bazel_greg/048a16ebf77b9527cde85d96a4fa6bbf/external/build_bazel_rules_nodejs/internal/jasmine_node_test/jasmine_node_test.bzl:45:5: 
        WARNING: @build_bazel_rules_nodejs will no longer provide jasmine_node_test at a later release
        Instead, add a devDependency on @bazel/jasmine
        and change the load statement to
        load("@npm_bazel_jasmine//:index.bzl", "jasmine_node_test")
        
INFO: Analyzed 8 targets (299 packages loaded, 7328 targets configured).
INFO: Found 5 targets and 3 test targets...
ERROR: /Users/greg/google/rules_nodejs/e2e/karma_typescript/BUILD.bazel:19:1: Compiling TypeScript (devmode) //:lib failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at /private/var/tmp/_bazel_greg/048a16ebf77b9527cde85d96a4fa6bbf/bazel-workers/worker-1-TypeScriptCompile.log ---8<---8<---
Error: @npm//@bazel/typescript/bin:tsc_wrapped_bin cannot find module '../tsc_wrapped/perf_trace' required by '/private/var/tmp/_bazel_greg/048a16ebf77b9527cde85d96a4fa6bbf/execroot/e2e_karma_typescript/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.runfiles/npm/node_modules/@bazel/typescript/internal/tsetse/runner.js'
  looked in:
    built-in, relative, absolute, nested node_modules - Error: Cannot find module '../tsc_wrapped/perf_trace'
    runfiles - Error: Cannot find module '/private/var/tmp/_bazel_greg/048a16ebf77b9527cde85d96a4fa6bbf/execroot/e2e_karma_typescript/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped/perf_trace'
    npm/node_modules - Error: Cannot find module '/private/var/tmp/_bazel_greg/048a16ebf77b9527cde85d96a4fa6bbf/execroot/e2e_karma_typescript/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.runfiles/npm/tsc_wrapped/perf_trace'
    node_modules attribute (npm/node_modules) - Error: Cannot find module '/private/var/tmp/_bazel_greg/048a16ebf77b9527cde85d96a4fa6bbf/execroot/e2e_karma_typescript/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.runfiles/npm/tsc_wrapped/perf_trace'

    at Function.module.constructor._resolveFilename (/private/var/tmp/_bazel_greg/048a16ebf77b9527cde85d96a4fa6bbf/execroot/e2e_karma_typescript/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped_bin_loader.js:472:17)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /private/var/tmp/_bazel_greg/048a16ebf77b9527cde85d96a4fa6bbf/execroot/e2e_karma_typescript/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.runfiles/npm/node_modules/@bazel/typescript/internal/tsetse/runner.js:15:23
    at /private/var/tmp/_bazel_greg/048a16ebf77b9527cde85d96a4fa6bbf/execroot/e2e_karma_typescript/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.runfiles/npm/node_modules/@bazel/typescript/internal/tsetse/runner.js:6:17
    at Object.<anonymous> (/private/var/tmp/_bazel_greg/048a16ebf77b9527cde85d96a4fa6bbf/execroot/e2e_karma_typescript/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.runfiles/npm/node_modules/@bazel/typescript/internal/tsetse/runner.js:12:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
---8<---8<--- End of log ---8<---8<---
INFO: Elapsed time: 34.913s, Critical Path: 1.33s
INFO: 7 processes: 6 darwin-sandbox, 1 worker.
FAILED: Build did NOT complete successfully
//:testing_chromium-local                                             NO STATUS
//:testing_firefox-local                                              NO STATUS
//:user_files_test                                                    NO STATUS

FAILED: Build did NOT complete successfully
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by gregmagolan** [comment]
I've only seen this once on CircieCI.

```
Running e2e test karma
checking deps: release
all deps built
+ yarn test
yarn run v1.13.0
warning package.json: No license field
$ bazel test ...
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=0
INFO: Reading rc options for 'test' from /home/circleci/rules_nodejs/common.bazelrc:
  Inherited 'common' options: --experimental_allow_incremental_repository_updates
INFO: Reading rc options for 'test' from /etc/bazel.bazelrc:
  Inherited 'build' options: --noshow_progress --announce_rc --local_resources=14336,8.0,1.0
INFO: Reading rc options for 'test' from /home/circleci/rules_nodejs/common.bazelrc:
  Inherited 'build' options: --symlink_prefix=dist/ --incompatible_strict_action_env
INFO: Reading rc options for 'test' from /home/circleci/rules_nodejs/common.bazelrc:
  'test' options: --test_output=errors --nolegacy_external_runfiles
INFO: Analyzed 2 targets (265 packages loaded, 6085 targets configured).
INFO: Found 2 test targets...
FAIL: //:testing_firefox-local (see /home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/execroot/e2e_karma/bazel-out/k8-fastbuild/testlogs/testing_firefox-local/test.log)
INFO: From Testing //:testing_firefox-local:
==================== Test output for //:testing_firefox-local:
WEB_TEST_METADATA=e2e_karma/testing_firefox-local.gen.json
TEST_LOGSPLITTER_OUTPUT_FILE=/home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/bazel-out/k8-fastbuild/testlogs/testing_firefox-local/test.raw_splitlogs/test.splitlogs
TEST_SIZE=large
TZ=UTC
OLDPWD=/home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma
TEST_PREMATURE_EXIT_FILE=/home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/bazel-out/k8-fastbuild/testlogs/testing_firefox-local/test.exited_prematurely
TEST_UNUSED_RUNFILES_LOG_FILE=/home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/bazel-out/k8-fastbuild/testlogs/testing_firefox-local/test.unused_runfiles_log
TEST_TEMPDIR=test_tempdir.DHKMjW
TEST_SRCDIR=/home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/bazel-out/k8-fastbuild/bin/testing_firefox-local.runfiles
GTEST_TMP_DIR=/home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/_tmp/cd6698b5281329ffa803da9b254d8f44
USER=circleci
TEST_TIMEOUT=900
TEST_TARGET=//:testing_firefox-local
PWD=/home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/bazel-out/k8-fastbuild/bin/testing_firefox-local.runfiles/e2e_karma
TEST_TMPDIR=/home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/_tmp/cd6698b5281329ffa803da9b254d8f44
XML_OUTPUT_FILE=/home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/bazel-out/k8-fastbuild/testlogs/testing_firefox-local/test.xml
TEST_UNDECLARED_OUTPUTS_DIR=/home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/bazel-out/k8-fastbuild/testlogs/testing_firefox-local/test.outputs
EXPERIMENTAL_SPLIT_XML_GENERATION=1
TEST_UNDECLARED_OUTPUTS_ANNOTATIONS_DIR=/home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/bazel-out/k8-fastbuild/testlogs/testing_firefox-local/test.outputs_manifest
TMPDIR=/tmp
TEST_WORKSPACE=e2e_karma
JAVA_RUNFILES=/home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/bazel-out/k8-fastbuild/bin/testing_firefox-local.runfiles
TEST_BINARY=./testing_firefox-local
RUN_UNDER_RUNFILES=1
PYTHON_RUNFILES=/home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/bazel-out/k8-fastbuild/bin/testing_firefox-local.runfiles
SHLVL=2
TEST_INFRASTRUCTURE_FAILURE_FILE=/home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/bazel-out/k8-fastbuild/testlogs/testing_firefox-local/test.infrastructure_failure
PATH=.:/bin:/usr/bin:/usr/local/bin
RUNFILES_DIR=/home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/bazel-out/k8-fastbuild/bin/testing_firefox-local.runfiles
TEST_WARNINGS_OUTPUT_FILE=/home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/bazel-out/k8-fastbuild/testlogs/testing_firefox-local/test.warnings
BASH_FUNC_is_absolute%%=() {  [[ "$1" = /* ]] || [[ "$1" =~ ^[a-zA-Z]:[/\\].* ]]
}
BASH_FUNC_rlocation%%=() {  if is_absolute "$1"; then
 echo "$1";
 else
 if [[ -e "$TEST_SRCDIR/$1" ]]; then
 echo "$TEST_SRCDIR/$1";
 else
 if [[ -e "$RUNFILES_MANIFEST_FILE" ]]; then
 echo "$(grep "^$1 " "$RUNFILES_MANIFEST_FILE" | sed 's/[^ ]* //')";
 fi;
 fi;
 fi
}
_=/usr/bin/printenv
Karma version: 4.0.1
25 07 2019 00:55:43.311:WARN [filelist]: All files matched by "/home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/bazel-out/k8-fastbuild/bin/testing_firefox-local.runfiles/e2e_karma/init-test.js" were excluded or matched by prior matchers.
25 07 2019 00:55:43.334:INFO [karma-server]: Karma v4.0.1 server started at http://0.0.0.0:9876/
25 07 2019 00:55:43.334:INFO [launcher]: Launching browsers FirefoxHeadless with concurrency unlimited
25 07 2019 00:55:43.338:INFO [launcher]: Starting browser FirefoxHeadless
25 07 2019 00:55:43.365:ERROR [launcher]: Cannot start FirefoxHeadless
    XPCOMGlueLoad error for file /home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/bazel-out/k8-fastbuild/bin/testing_firefox-local.runfiles/e2e_karma/firefox/libxul.so:
libdbus-glib-1.so.2: cannot open shared object file: No such file or directory
Couldn't load XPCOM.

25 07 2019 00:55:43.365:ERROR [launcher]: FirefoxHeadless stdout: 
25 07 2019 00:55:43.365:ERROR [launcher]: FirefoxHeadless stderr: XPCOMGlueLoad error for file /home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/bazel-out/k8-fastbuild/bin/testing_firefox-local.runfiles/e2e_karma/firefox/libxul.so:
libdbus-glib-1.so.2: cannot open shared object file: No such file or directory
Couldn't load XPCOM.

25 07 2019 00:55:43.367:INFO [launcher]: Trying to start FirefoxHeadless again (1/2).
25 07 2019 00:55:43.391:ERROR [launcher]: Cannot start FirefoxHeadless
    XPCOMGlueLoad error for file /home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/bazel-out/k8-fastbuild/bin/testing_firefox-local.runfiles/e2e_karma/firefox/libxul.so:
libdbus-glib-1.so.2: cannot open shared object file: No such file or directory
Couldn't load XPCOM.

25 07 2019 00:55:43.391:ERROR [launcher]: FirefoxHeadless stdout: 
25 07 2019 00:55:43.392:ERROR [launcher]: FirefoxHeadless stderr: XPCOMGlueLoad error for file /home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/bazel-out/k8-fastbuild/bin/testing_firefox-local.runfiles/e2e_karma/firefox/libxul.so:
libdbus-glib-1.so.2: cannot open shared object file: No such file or directory
Couldn't load XPCOM.

25 07 2019 00:55:43.392:INFO [launcher]: Trying to start FirefoxHeadless again (2/2).
25 07 2019 00:55:43.416:ERROR [launcher]: Cannot start FirefoxHeadless
    XPCOMGlueLoad error for file /home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/bazel-out/k8-fastbuild/bin/testing_firefox-local.runfiles/e2e_karma/firefox/libxul.so:
libdbus-glib-1.so.2: cannot open shared object file: No such file or directory
Couldn't load XPCOM.

25 07 2019 00:55:43.416:ERROR [launcher]: FirefoxHeadless stdout: 
25 07 2019 00:55:43.416:ERROR [launcher]: FirefoxHeadless stderr: XPCOMGlueLoad error for file /home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/sandbox/processwrapper-sandbox/8/execroot/e2e_karma/bazel-out/k8-fastbuild/bin/testing_firefox-local.runfiles/e2e_karma/firefox/libxul.so:
libdbus-glib-1.so.2: cannot open shared object file: No such file or directory
Couldn't load XPCOM.

25 07 2019 00:55:43.417:ERROR [launcher]: FirefoxHeadless failed 2 times (cannot start). Giving up.
================================================================================
INFO: Elapsed time: 37.111s, Critical Path: 10.24s
INFO: 11 processes: 11 processwrapper-sandbox.
//:testing_chromium-local                                                PASSED in 1.8s
//:testing_firefox-local                                                 FAILED in 6.7s
  /home/circleci/.cache/bazel/_bazel_circleci/1e998998f6338a02e8294edc130b3453/execroot/e2e_karma/bazel-out/k8-fastbuild/testlogs/testing_firefox-local/test.log

Executed 2 out of 2 tests: 1 test passes and 1 fails locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

**Comment by gregmagolan** [comment]
Flake observed in e2e test karma_stack_strace. On a subsequent 2nd run it passed. Leaving this here as a record incase it keeps coming up. Failure on first run of test was `Did not find 'failing.spec.ts:7:17' in Karma stack trace`. Complete output was:

```
Running e2e test karma_stack_trace
checking deps: release karma typescript
all deps built
+ yarn test
yarn run v1.13.0
warning package.json: No license field
$ ../../scripts/link_deps.sh
checking deps: release karma typescript
all deps built
$ bazel test ...
Starting local Bazel server and connecting to it...
DEBUG: /private/var/tmp/_bazel_greg/2990d992581b2cb0f715cf37d5e50b5f/external/bazel_skylib/skylark_library.bzl:1:1: WARNING: skylark_library.bzl is deprecated and will go away in the future, please use bzl_library.bzl instead.
INFO: Analysed 4 targets (299 packages loaded, 10278 targets configured).
INFO: Found 3 targets and 1 test target...
FAIL: //:test_sourcemap (see /private/var/tmp/_bazel_greg/2990d992581b2cb0f715cf37d5e50b5f/execroot/e2e_karma_stack_trace/bazel-out/darwin-fastbuild/testlogs/test_sourcemap/test.log)
INFO: From Testing //:test_sourcemap:
==================== Test output for //:test_sourcemap:
Did not find 'failing.spec.ts:7:17' in Karma stack trace
================================================================================
INFO: Elapsed time: 25.821s, Critical Path: 18.22s
INFO: 7 processes: 7 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 9 total actions
//:test_sourcemap                                                        FAILED in 4.9s
  /private/var/tmp/_bazel_greg/2990d992581b2cb0f715cf37d5e50b5f/execroot/e2e_karma_stack_trace/bazel-out/darwin-fastbuild/testlogs/test_sourcemap/test.log

INFO: Build completed, 1 test FAILED, 9 total actions
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
greg@macbook rules_nodejs (chores/add-examples) $ 
greg@macbook rules_nodejs (chores/add-examples) $ 
greg@macbook rules_nodejs (chores/add-examples) $ cat /private/var/tmp/_bazel_greg/2990d992581b2cb0f715cf37d5e50b5f/execroot/e2e_karma_stack_trace/bazel-out/darwin-fastbuild/testlogs/test_sourcemap/test.log
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //:test_sourcemap
-----------------------------------------------------------------------------
Did not find 'failing.spec.ts:7:17' in Karma stack trace
greg@macbook rules_nodejs (chores/add-examples) $ ./scripts/test_e2e.sh karma_stack_trace


Running e2e test karma_stack_trace
checking deps: release karma typescript
all deps built
+ yarn test
yarn run v1.13.0
warning package.json: No license field
$ ../../scripts/link_deps.sh
checking deps: release karma typescript
all deps built
$ bazel test ...
DEBUG: /private/var/tmp/_bazel_greg/2990d992581b2cb0f715cf37d5e50b5f/external/bazel_skylib/skylark_library.bzl:1:1: WARNING: skylark_library.bzl is deprecated and will go away in the future, please use bzl_library.bzl instead.
INFO: Analysed 4 targets (1 packages loaded, 2 targets configured).
INFO: Found 3 targets and 1 test target...
INFO: Elapsed time: 13.282s, Critical Path: 12.32s
INFO: 7 processes: 7 darwin-sandbox.
INFO: Build completed successfully, 9 total actions
//:test_sourcemap                                                        PASSED in 2.8s

Executed 1 out of 1 test: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these arINFO: Build completed successfully, 9 total actions
✨  Done in 13.51s.
```
