### ISSUE TITLE
Angular Ivy - Symbol TestDirective declared in ... is not exported from

### ISSUE THREAD

**Issue by moczix** [bazelbuild/rules_nodejs#1378]
HI! there is a problem with angular ivy, bazel aot mode. This problem is still alive since next9 (before i dont know).

here is repro repo: https://github.com/moczix/ng-bazel-test

Im using module_name in each ng_module to use paths with alias @something and this is an isue, 

this issue is only with aot mode, not with legacy. I have src/shared/shared.module and i import it like alias import { SharedModule } from '@shared/shared.module' and in my bazel definition i have

```
ng_module(
    name = "shared",
    module_name = "@shared", # when i comment this and import this module relative all works
    srcs = glob(
        include = ["*.ts"],
        exclude = [
        ],
    ),
    assets = [],
    deps = [
        "@npm//@angular/core",
        "@npm//@angular/platform-browser",
        "@npm//@angular/router",
        "@npm//@types",
        "@npm//rxjs",
    ],
)
```

errors: 
```
Error: Symbol TestDirective declared in /home/moczix/.cache/bazel/_bazel_moczix/30201c43893c127855d3433fc2b20c13/execroot/project/bazel-out/k8-fastbuild/bin/src/shared/test-directive.d.ts is not exported from @shared/shared.module (import into /home/moczix/.cache/bazel/_bazel_moczix/30201c43893c127855d3433fc2b20c13/execroot/project/src/app/app.component.ts)
    at AbsoluteModuleStrategy.emit (/home/moczix/.cache/bazel/_bazel_moczix/30201c43893c127855d3433fc2b20c13/execroot/project/bazel-out/host/bin/external/npm/@angular/bazel/bin/ngc-wrapped.sh.runfiles/npm/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:125:23)
    at ReferenceEmitter.emit (/home/moczix/.cache/bazel/_bazel_moczix/30201c43893c127855d3433fc2b20c13/execroot/project/bazel-out/host/bin/external/npm/@angular/bazel/bin/ngc-wrapped.sh.runfiles/npm/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:42:44)
    at ComponentDecoratorHandler.resolve (/home/moczix/.cache/bazel/_bazel_moczix/30201c43893c127855d3433fc2b20c13/execroot/project/bazel-out/host/bin/external/npm/@angular/bazel/bin/ngc-wrapped.sh.runfiles/npm/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/component.js:416:62)
    at /home/moczix/.cache/bazel/_bazel_moczix/30201c43893c127855d3433fc2b20c13/execroot/project/bazel-out/host/bin/external/npm/@angular/bazel/bin/ngc-wrapped.sh.runfiles/npm/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:279:57
    at Map.forEach (<anonymous>)
    at IvyCompilation.resolve (/home/moczix/.cache/bazel/_bazel_moczix/30201c43893c127855d3433fc2b20c13/execroot/project/bazel-out/host/bin/external/npm/@angular/bazel/bin/ngc-wrapped.sh.runfiles/npm/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:270:29)
    at NgtscProgram.ensureAnalyzed (/home/moczix/.cache/bazel/_bazel_moczix/30201c43893c127855d3433fc2b20c13/execroot/project/bazel-out/host/bin/external/npm/@angular/bazel/bin/ngc-wrapped.sh.runfiles/npm/node_modules/@angular/compiler-cli/src/ngtsc/program.js:281:34)
    at NgtscProgram.getNgSemanticDiagnostics (/home/moczix/.cache/bazel/_bazel_moczix/30201c43893c127855d3433fc2b20c13/execroot/project/bazel-out/host/bin/external/npm/@angular/bazel/bin/ngc-wrapped.sh.runfiles/npm/node_modules/@angular/compiler-cli/src/ngtsc/program.js:189:36)
    at gatherDiagnosticsForInputsOnly (/home/moczix/.cache/bazel/_bazel_moczix/30201c43893c127855d3433fc2b20c13/execroot/project/bazel-out/host/bin/external/npm/@angular/bazel/bin/ngc-wrapped.sh.runfiles/npm/node_modules/@angular/bazel/src/ngc-wrapped/index.js:425:43)
    at gatherDiagnostics (/home/moczix/.cache/bazel/_bazel_moczix/30201c43893c127855d3433fc2b20c13/execroot/project/bazel-out/host/bin/external/npm/@angular/bazel/bin/ngc-wrapped.sh.runfiles/npm/node_modules/@angular/bazel/src/ngc-wrapped/index.js:338:46)
    at Object.performCompilation (/home/moczix/.cache/bazel/_bazel_moczix/30201c43893c127855d3433fc2b20c13/execroot/project/bazel-out/host/bin/external/npm/@angular/bazel/bin/ngc-wrapped.sh.runfiles/npm/node_modules/@angular/compiler-cli/src/perform_compile.js:234:72)
    at compile (/home/moczix/.cache/bazel/_bazel_moczix/30201c43893c127855d3433fc2b20c13/execroot/project/bazel-out/host/bin/external/npm/@angular/bazel/bin/ngc-wrapped.sh.runfiles/npm/node_modules/@angular/bazel/src/ngc-wrapped/index.js:340:57)
    at runOneBuild (/home/moczix/.cache/bazel/_bazel_moczix/30201c43893c127855d3433fc2b20c13/execroot/project/bazel-out/host/bin/external/npm/@angular/bazel/bin/ngc-wrapped.sh.runfiles/npm/node_modules/@angular/bazel/src/ngc-wrapped/index.js:117:33)
    at Object.<anonymous> (/home/moczix/.cache/bazel/_bazel_moczix/30201c43893c127855d3433fc2b20c13/execroot/project/bazel-out/host/bin/external/npm/@angular/bazel/bin/ngc-wrapped.sh.runfiles/npm/node_modules/@bazel/typescript/internal/tsc_wrapped/worker.js:166:53)
    at Generator.next (<anonymous>)
    at fulfilled (/home/moczix/.cache/bazel/_bazel_moczix/30201c43893c127855d3433fc2b20c13/execroot/project/bazel-out/host/bin/external/npm/@angular/bazel/bin/ngc-wrapped.sh.runfiles/npm/node_modules/@bazel/typescript/internal/tsc_wrapped/worker.js:3:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by JaredNeil** [comment]
I just ran into this issue when switching from `ng_module` to `ts_library` + `use_angular_plugin = True`.

As for the example above, this diff does resolve the error, but seems like it shouldn't be needed.
```diff
diff --git a/src/shared/shared.module.ts b/src/shared/shared.module.ts
index 8f76d59..586a7dc 100644
--- a/src/shared/shared.module.ts
+++ b/src/shared/shared.module.ts
@@ -1,6 +1,7 @@
 import { NgModule } from "@angular/core";
 import { CommonModule } from "@angular/common";
 import { TestDirective } from "./test-directive";
+export { TestDirective } from "./test-directive";
 
 @NgModule({
   declarations: [
```

The generated `app.component.mjs` does contain:
```
import * as i1 from "@shared/shared.module";
...
directives: [i1.TestDirective, i2.NgSwitch, i2.NgSwitchDefault, i2.NgSwitchCase, i3.RouterOutlet]
```

I'm not sure what's different about this and our setup with `ng_module`, or what changed with `ts_library` to cause it to crop up now. We do use `tsickle`, but I still get the same error if I change the example to use tsickle as well.

**Comment by alexeagle** [comment]
👀 I don't know where to start with this either, I think someone with recent Angular compiler knowledge needs to dig a bit deeper to see what's different between these. It's also not clear to me if it's a regression, or if allowing this previously had been a bug.

**Comment by JaredNeil** [comment]
Okay, I'm getting close. In the example, if I change `angularCompilerOptions._useHostForImportGeneration` to `true` in the generated tsconfig (`bazel-out/k8-fastbuild/bin/src/app/app_es5_tsconfig.json`), then it works. This hasn't been a problem for us before because we have been using a patch to the angular compiler that accomplishes the same thing.

```diff
--- a/node_modules/@angular/compiler-cli/src/ngtsc/core/src/compiler.js
+++ b/node_modules/@angular/compiler-cli/src/ngtsc/core/src/compiler.js
@@ -544,7 +544,7 @@
             // Construct the ReferenceEmitter.
             var refEmitter;
             var aliasingHost = null;
-            if (this.host.unifiedModulesHost === null || !this.options._useHostForImportGeneration) {
+            if (this.host.unifiedModulesHost === null) {
                 var localImportStrategy = void 0;
                 // The strategy used for local, in-project imports depends on whether TS has been configured
                 // with rootDirs. If so, then multiple directories may be mapped in the same "module
```

Any idea how we might accomplish something similar with `ts_library` + `use_angular_plugin = True`?

**Comment by JaredNeil** [comment]
Okay, so with `ng_module` `this.host.unifiedModulesHost === this.host`, but with `ts_library` `this.host.unifiedModulesHost === null`. Looks like that's because [`fileNameToModuleName` is not defined](https://github.com/angular/angular/blob/e648a0c4ca532a009186855c2ed998188fe0c9e3/packages/compiler-cli/src/ngtsc/core/src/host.ts#L272-L274).

**Comment by JaredNeil** [comment]
Aliasing `host.fileNameToModuleId` as `host.fileNameToModuleName`, seems to work. I'm not sure if those are meant to be the same, or if it just happens to work.
