### ISSUE TITLE
nodejs_binary sometimes includes duplicate workspace name path in location

### ISSUE THREAD

**Issue by marcus-sa** [bazelbuild/rules_nodejs#1403]
# 🐞 bug report

### Affected Rule
The issue is caused by the rule: `nodejs_binary`

### Is this a regression?
Most likely

### Description
When `nodejs_binary` resolves `$(location)` for certain files (most likely non JS sources) it sometimes includes your workspace name twice in the path.

If you look at the exception below, you'll see that the config path contains `bazel-out/k8-fastbuild/bin/src/lint.sh.runfiles/eslint_test/eslint_test/.eslintrc` instead of just `bazel-out/k8-fastbuild/bin/src/lint.sh.runfiles/eslint_test/.eslintrc`

So `eslint_test/eslint_test` should be `eslint_test`

## 🔬 Minimal Reproduction
```
$ yarn && yarn bazel run //src:lint
```

> .bazelrc
```
build --experimental_allow_incremental_repository_updates
query --experimental_allow_incremental_repository_updates

test --test_output=errors

build --symlink_prefix=dist/

test:debug --test_output=streamed --test_strategy=exclusive --test_timeout=9999 --nocache_test_results --define=VERBOSE_LOGS=1

run:debug --define=VERBOSE_LOGS=1 -- --node_options=--inspect-brk
```

> package.json
```json
{
	"devDependencies": {
    	"@bazel/bazel": "1.2.0",
    	"@bazel/hide-bazel-files": "0.42.1",
    	"eslint": "6.7.1",
	}
}
```

> WORKSPACE
```python
workspace(
    name = "eslint_test",
    managed_directories = {"@npm": ["node_modules"]},
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "c612d6b76eaa17540e8b8c806e02701ed38891460f9ba3303f4424615437887a",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/0.42.1/rules_nodejs-0.42.1.tar.gz"],
)

# Setup the Node.js toolchain
load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories", "yarn_install")

node_repositories(package_json = ["//:package.json"])

yarn_install(
    # Name this npm so that Bazel Label references look like @npm//package
    name = "npm",
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)

load("@npm//:install_bazel_dependencies.bzl", "install_bazel_dependencies")

install_bazel_dependencies()
```

> BUILD
```python
package(default_visibility = ["//visibility:public"])

exports_files([
    ".eslintrc",
])
```

> .eslintrc
```
{
	// ...
}
```

> tools/BUILD
```

```

> tools/eslint.bzl

```python
load("@build_bazel_rules_nodejs//:index.bzl", "nodejs_binary")

def eslint(config, srcs, deps = [], **kwargs):
    data = deps + [
        "@npm//eslint",
        config,
    ]

    files = ["$(location %s)" % f for f in srcs]
    args = [
        "-c",
        "$(location %s)" % config,
    ] + files

    nodejs_binary(
        data = data + srcs,
        entry_point = "@npm//:node_modules/eslint/bin/eslint.js",
        templated_args = args,
        **kwargs
    )
```

> src/BUILD
```python
load("//tools:eslint.bzl", "eslint")

eslint(
	name = "lint",
	srcs = ["index.js"],
	config = "//:.eslintrc",
)

```

> src/index.js
```js
// ...
```

## 🔥 Exception or Error
```sh
Error: Cannot read config file: /home/marcus-sa/.cache/bazel/_bazel_marcus-sa/19567ae4fb6047d3fbed7db3cb2f3387/execroot/eslint_test/bazel-out/k8-fastbuild/bin/src/lint.sh.runfiles/eslint_test/eslint_test/.eslintrc
Error: ENOENT: no such file or directory, open '/home/marcus-sa/.cache/bazel/_bazel_marcus-sa/19567ae4fb6047d3fbed7db3cb2f3387/execroot/eslint_test/bazel-out/k8-fastbuild/bin/src/lint.sh.runfiles/eslint_test/eslint_test/.eslintrc'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at readFile (node_modules/eslint/lib/cli-engine/config-array-factory.js:117:15)
    at loadLegacyConfigFile (node_modules/eslint/lib/cli-engine/config-array-factory.js:182:44)
    at loadConfigFile (node_modules/eslint/lib/cli-engine/config-array-factory.js:295:20)
    at ConfigArrayFactory._loadConfigData (node_modules/eslint/lib/cli-engine/config-array-factory.js:494:13)
    at ConfigArrayFactory.loadFile (node_modules/eslint/lib/cli-engine/config-array-factory.js:414:18)
    at createCLIConfigArray (node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:157:35)
    at new CascadingConfigArrayFactory (node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:218:29)
    at new CLIEngine (node_modules/eslint/lib/cli-engine/cli-engine.js:563:36)
```

## 🌍  Your Environment

**Operating System:**
```
Ubuntu Server 19.10
```

**Output of `bazel version`:**
```sh
Build label: 1.2.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 20 15:04:55 2019 (1574262295)
Build timestamp: 1574262295
Build timestamp as int: 1574262295
```

**Rules version (SHA):**
```python
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "c612d6b76eaa17540e8b8c806e02701ed38891460f9ba3303f4424615437887a",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/0.42.1/rules_nodejs-0.42.1.tar.gz"],
)
```

**Anything else relevant?**
This happens with other `nodejs_binary` targets as well which tries to include non JS sources

**Comment by arjantop** [comment]
Another possibly related affected case is (probably) when using  the `cluster` module:
```
Error: Cannot find module '/cache/bazel/output_base/execroot/test/bazel-out/k8-fastbuild/bin/services/my-service/app.sh.runfiles/test/test/services/my-service/app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Master: Worker 26572 from slot 0 exited with code 1 (signal: null).
```

Workspace name is `test` and does also appear twice in the path `test/test`.

Bazel version and rules_nodejs are the same as above. Running on Mac OS Catalina.

I also tried going a couple of versions back (to around 0.37) and the problem persisted.

**Comment by marcus-sa** [comment]
@alexeagle any clue as to why this is happening? I'd like to contribute since it's becoming critical, but got no clue as where to look.

**Comment by Toxicable** [comment]
I've also seen this reproduced in here https://github.com/bazelbuild/rules_nodejs/pull/1530
I cant remember the exact config, but it's some combination of running the server and disabling the require patches

**Comment by gregmagolan** [comment]
I've fixed up some bug in the custom $(location) expansion here: https://github.com/bazelbuild/rules_nodejs/pull/1524.

This also adds support for $(rootpath) and $(execpath) which I would recommend using going forward as $(location) in templated_args behaves differently than $(locaiton) in args. Also, Bazel docs recommend not even using $(location) in args. See https://docs.bazel.build/versions/master/be/make-variables.html#predefined_label_variables:

```
location: A synonym for either execpath or rootpath, depending on the attribute being expanded. This is legacy pre-Starlark behavior and not recommended unless you really know what it does for a particular rule. See #2475 for details.
```

Hoping to land #1524  this week and cut another release. I don't know if it will fix this particular issue but it may.

**Comment by marcus-sa** [comment]
@gregmagolan I've just always gone with `$(location)` because all examples used it, but awesome.
I'll test it out when it lands and let you know :smile:

**Comment by benlesh** [comment]
@alexeagle @evahowe I'm hitting this issue at work trying to use `cluster`. Can we reopen this? What work needs to be done to fix this? How can we help?
