### ISSUE TITLE
Build fails when including paralleljs

### ISSUE THREAD

**Issue by cshunger** [bazelbuild/rules_nodejs#1448]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

yarn_install/npm_install

### Is this a regression?

Unsure

### Description

After including paralleljs the `bazel build //...` fails due to an invalid package.json format. The package.json format does not look to be out of the ordinary and can be processed by other tools like `jq`
https://github.com/parallel-js/parallel.js/blob/master/package.json

## 🔬 Minimal Reproduction

Using the [example/nestjs](https://github.com/bazelbuild/rules_nodejs/tree/master/examples/nestjs) 

Do `yarn add paralleljs` then `bazel build. //...`

## 🔥 Exception or Error

<pre><code>
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
	File "/home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 383
		_create_build_files(repository_ctx, "yarn_install", node, ...)
	File "/home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 150, in _create_build_files
		fail(("generate_build_file.js failed:...)))
generate_build_file.js failed: 
STDOUT:

STDERR:
undefined:1
{
^

SyntaxError: Unexpected token ﻿ in JSON at position 0
    at JSON.parse (<anonymous>)
    at parsePackage (/home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:471:48)
    at /home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:440:23
    at Array.forEach (<anonymous>)
    at findPackages (/home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:435:18)
    at main (/home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:97:22)
    at /home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:72:9
    at /home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:3:17
    at Object.<anonymous> (/home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
ERROR: no such package '@npm//': Traceback (most recent call last):
	File "/home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 383
		_create_build_files(repository_ctx, "yarn_install", node, ...)
	File "/home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 150, in _create_build_files
		fail(("generate_build_file.js failed:...)))
generate_build_file.js failed: 
STDOUT:

STDERR:
undefined:1
{
^

SyntaxError: Unexpected token ﻿ in JSON at position 0
    at JSON.parse (<anonymous>)
    at parsePackage (/home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:471:48)
    at /home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:440:23
    at Array.forEach (<anonymous>)
    at findPackages (/home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:435:18)
    at main (/home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:97:22)
    at /home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:72:9
    at /home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:3:17
    at Object.<anonymous> (/home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
ERROR: no such package '@npm//': Traceback (most recent call last):
	File "/home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 383
		_create_build_files(repository_ctx, "yarn_install", node, ...)
	File "/home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 150, in _create_build_files
		fail(("generate_build_file.js failed:...)))
generate_build_file.js failed: 
STDOUT:

STDERR:
undefined:1
{
^

SyntaxError: Unexpected token ﻿ in JSON at position 0
    at JSON.parse (<anonymous>)
    at parsePackage (/home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:471:48)
    at /home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:440:23
    at Array.forEach (<anonymous>)
    at findPackages (/home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:435:18)
    at main (/home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:97:22)
    at /home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:72:9
    at /home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:3:17
    at Object.<anonymous> (/home/cshunger/.cache/bazel/_bazel_cshunger/e48e55cf1f507300f5a6e65defb96cd1/external/npm/generate_build_file.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
ubuntu
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
1.0.0
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
a54b2511d6dae42c1f7cdaeb08144ee2808193a088004fc3b464a04583d5aa2e
  </code>
</pre>

**Anything else relevant?**
```
cat -A paralleljs/package.json
M-oM-;M-?{$
^I"name": "paralleljs",$
^I"version": "0.2.1",$
^I"author": "Adam Savitzky <adam.savitzky@gmail.com>",$
^I"contributors": [$
^I^I"Sebastian Mayr <sebmaster16@gmail.com> (http://s3bmaster.blogspot.co.at/)"$
^I],$
^I"description": "parallel.js enables easy multi-thread processing in javascript",$
^I"main": "lib/parallel.js",$
^I"repository": {$
^I^I"type": "git",$
^I^I"url": "https://github.com/adambom/parallel.js.git"$
^I},$
^I"directories": {$
^I^I"lib": "lib",$
^I^I"test": "test"$
^I},$
^I"keywords": [$
^I^I"parallel",$
^I^I"spawn",$
^I^I"map",$
^I^I"thread",$
^I^I"parallel.js",$
^I^I"workers",$
^I^I"webworkers"$
^I],$
^I"devDependencies": {$
^I^I"jasmine-node": "x",$
^I^I"q": "x"$
^I},$
^I"license": "BSD",$
^I"scripts": {$
^I^I"test": "jasmine-node --verbose test/specs"$
^I},$
^I"engines": {$
^I^I"node": ">=0.9.10"$
^I},$
^I"testling" : {$
^I^I"scripts": [$
^I^I^I"test/lib/jasmine/jasmine.js",$
^I^I^I"test/specs/*.js",$
^I^I^I"test/runner.js"$
^I^I]$
^I}$
}%          
```

**Comment by alexeagle** [comment]
That package.json is interesting! It starts with three strange bytes before the opening curly brace. 

```
$ od -xc node_modules/paralleljs/package.json
0000000    bbef    7bbf    090a    6e22    6d61    2265    203a    7022
        357 273 277   {  \n  \t   "   n   a   m   e   "   :       "   p

$ file -bi node_modules/paralleljs/package.json
text/plain; charset=utf-8
```

utf-8 but I dunno what that garbage is. The real question is just, are we parsing the package.json in a way we shouldn't.?

let's see in node:

```
> JSON.parse('node_modules/paralleljs/package.json')
SyntaxError: Unexpected token o in JSON at position 1

> require('./node_modules/paralleljs/package.json').name
'paralleljs'
```

I guess we could fix this bug by using require() instead. Maybe @clydin has some opinion on that

**Comment by alexeagle** [comment]
Ah, I'm learning. These three bites are The UTF-8 representation of the BOM is the (hexadecimal) byte sequence 0xEF,0xBB,0xBF. Looks easy to strip.

**Comment by Toxicable** [comment]
A BOM is considered white space so doing a `trim` on the JSON string should strip it
```
> JSON.parse(fs.readFileSync('node_modules/paralleljs/package.json', 'utf8'))
Thrown:
SyntaxError: Unexpected token ﻿ in JSON at position 0

>JSON.parse(fs.readFileSync('node_modules/paralleljs/package.json', 'utf8').trim())
{                                                                                                                         
    name: 'paralleljs',  
```

**Comment by clydin** [comment]
Yes. It’s the UTF8 BOM.  Windows systems have a tendency to add it to files and can be safely stripped.
