### ISSUE TITLE
pkg_npm not compatible with output from `rollup_bundle(output_dir = True)`

### ISSUE THREAD

**Issue by joeljeske** [bazelbuild/rules_nodejs#1567]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

pkg_npm 

### Is this a regression?

 I do not think so

### Description

 A clear and concise description of the problem...

pkg_npm is unable to make an archive using outputs that are directories. This might typically happen when using `rollup_bundle(output_dir = True)` to create a bundle with multiple chunks, however `rollup_bundle` declares a directory rather than the individual files. This results in an output that cannot be added to a pkg_npm archive.

## 🔬 Minimal Reproduction

```
ts_library(
  name = "compile",
  srcs = glob(["*.ts"]),
  tsconfig = '//:tsconfig.json',
)

rollup_bundle(
   name = "bundle",
   entry_point = "index.ts"
   deps = ["compile"],
   format = "esm",
   output_dir = True
)

pkg_npm(
  name = "npm",
  srcs = ["package.json"],
  deps = ["bundle"],
)
```

## 🔥 Exception or Error

<pre><code>
Error: Path provided was not a file!
    at isStatFile (/private/var/tmp/_bazel_user/abc123/sandbox/darwin-sandbox/1/execroot/project/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/pkg_npm/packager.sh.runfiles/build_bazel_rules_nodejs/third_party/github.com/gjtorikian/isBinaryFile/src/index.js:257:11)
    at isBinaryFileSync (/private/var/tmp/_bazel_user/abc123/sandbox/darwin-sandbox/1/execroot/project/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/pkg_npm/packager.sh.runfiles/build_bazel_rules_nodejs/third_party/github.com/gjtorikian/isBinaryFile/src/index.js:167:5)
    at copyWithReplace (/private/var/tmp/_bazel_user/abc123/sandbox/darwin-sandbox/1/execroot/project/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/pkg_npm/packager.sh.runfiles/build_bazel_rules_nodejs/internal/pkg_npm/packager.js:34:8)
    at main (/private/var/tmp/_bazel_user/abc123/sandbox/darwin-sandbox/1/execroot/project/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/pkg_npm/packager.sh.runfiles/build_bazel_rules_nodejs/internal/pkg_npm/packager.js:143:7)
    at Object.<anonymous> (/private/var/tmp/_bazel_user/abc123/sandbox/darwin-sandbox/1/execroot/project/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/pkg_npm/packager.sh.runfiles/build_bazel_rules_nodejs/internal/pkg_npm/packager.js:185:22)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Object.<anonymous> (/private/var/tmp/ca38e9361951c2708a9402d836e79bb6/sandbox/darwin-sandbox/1/execroot/project/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/pkg_npm/packager.sh.runfiles/build_bazel_rules_nodejs/internal/pkg_npm/packager_loader.js:32:24)

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS 10.14.6
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 1.2.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 20 15:08:12 2019 (1574262492)
Build timestamp: 1574262492
Build timestamp as int: 1574262492
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
1.1.0
c97bf38546c220fa250ff2cc052c1a9eac977c662c1fc23eda797b0ce8e70a43
  </code>
</pre>

**Anything else relevant?**

**Comment by marcus-sa** [comment]
It might be because of your typos:
```python
ts_library(
  name = "compile",
  srcs = glob(["*.ts"]),
  tsconfig = '//:tsconfig.json',
)

rollup_bundle(
   name = "bundle",
   entry_point = "index.ts"
   deps = [":compile"],
   format = "esm",
   output_dir = True
)

pkg_npm(
  name = "npm",
  srcs = ["package.json"],
  deps = [":bundle"],
)
```

dependencies should be referenced by their target label by prefixing with `:`

**Comment by joeljeske** [comment]
Colons are optional and only a matter of convention 
https://docs.bazel.build/versions/master/build-ref.html#labels

>Within a BUILD file, the package-name part of label may be omitted, and optionally the colon too. So within the BUILD file for package my/app (i.e. //my/app:BUILD), the following "relative" labels are all equivalent:
>
> ```
>//my/app:app
>//my/app
>:app
>app
>```
>
>(It is a matter of convention that the colon is omitted for files, but retained for rules, but it is not otherwise significant.)


However, I did write up the example build code quickly for this ticket, it is not exactly from my codebase, but it gives the general idea.

**Comment by joeljeske** [comment]
I am currently using this patch to check for directories and copy their contents into the npm archive.

[rules_nodejs-1.1.0-c97bf38546c220fa250ff2cc052c1a9eac977c662c1fc23eda797b0ce8e70a43.patch.txt](https://github.com/bazelbuild/rules_nodejs/files/4095156/rules_nodejs-1.1.0-c97bf38546c220fa250ff2cc052c1a9eac977c662c1fc23eda797b0ce8e70a43.patch.txt)


 It seems using directories is frowned upon in Bazel, but I am not sure what any better way would be since Rollup is deciding where to chunk modules, and not something that is necessarily obvious or statically analyzable.

**Comment by nickbehrens** [comment]
@joeljeske would you mind turning your patch into a PR?  I agree we should be special casing directories in this code.

**Comment by joeljeske** [comment]
@nickbehrens thanks for the invitation! I just finished posting a PR for the change.
