### ISSUE TITLE
rollup config claims support for multiple root dirs; not actually possible

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#171]
Internally, rollup resolves relative imports without asking the resolver plugin.

In angular's `ng_rollup_bundle` it looks like 
```
[!] Error: Could not resolve './internal/Observable' from ../../../../execroot/angular/bazel-out/k8-fastbuild/bin/external/rxjs/rxjs.esm5/external/rxjs/index.js
Error: Could not resolve './internal/Observable' from ../../../../execroot/angular/bazel-out/k8-fastbuild/bin/external/rxjs/rxjs.esm5/external/rxjs/index.js
    at error (/usr/local/google/home/alexeagle/.cache/bazel/_bazel_alexeagle/5c094f47f582dc47fc598194e749d5c0/external/build_bazel_rules_nodejs_rollup_deps/node_modules/rollup/dist/rollup.js:189:14)
    at then.resolvedId (/usr/local/google/home/alexeagle/.cache/bazel/_bazel_alexeagle/5c094f47f582dc47fc598194e749d5c0/external/build_bazel_rules_nodejs_rollup_deps/node_modules/rollup/dist/rollup.js:18303:8)
    at <anonymous>
```

This means that no matter how correct our module resolution logic is, it will never work for two different rootDirs to have a relative import between them. We cannot have the same semantics as TypeScript path mapping.

It seems that we just have to force callers of rollup to flatten into a single root via some other action before they pass inputs to `rollup_bundle` or other deriving rules.

/cc @mrmeku this is the same thing we had to do for closure compiler already.

**Comment by alexeagle** [comment]
Resolved this by removing the feature - callers must now flatten the input trees to a single root before handing it to rollup_bundle
