### ISSUE TITLE
//internal/pkg_npm/test/linking:test fails on Windows with remote caching enabled

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_nodejs#1781]
# 🐞 bug report

### Is this a regression?

No, the test is added recently

### Description

`//internal/pkg_npm/test/linking:test` will fail in a second run with remote caching enabled.

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1446#b6409cc9-0a26-4ddd-8828-74d639131091

## 🔬 Minimal Reproduction

```
bazel test //internal/pkg_npm/test/linking:test
bazel clean --expunge & rm -rf node_modules
bazel test //internal/pkg_npm/test/linking:test
```

## 🔥 Exception or Error

<pre><code>
Executing tests from //internal/pkg_npm/test/linking:test
-----------------------------------------------------------------------------
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module '@scoped/bar'
Require stack:
- C:\b\s7rxdkmr\execroot\build_bazel_rules_nodejs\bazel-out\x64_windows-fastbuild\bin\internal\pkg_npm\test\linking\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\b\s7rxdkmr\execroot\build_bazel_rules_nodejs\bazel-out\x64_windows-fastbuild\bin\internal\pkg_npm\test\linking\main.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\b\\s7rxdkmr\\execroot\\build_bazel_rules_nodejs\\bazel-out\\x64_windows-fastbuild\\bin\\internal\\pkg_npm\\test\\linking\\main.js'
  ]
}
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
3.0.0rc2
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
HEAD
  </code>
</pre>

**Comment by gregmagolan** [comment]
Thanks for the repo steps. I am able to reproduce on Windows. Doesn't happen on OSX. Haven't tried linux.
