### ISSUE TITLE
bazel is not defined during rollup build

### ISSUE THREAD

**Issue by kylecannon** [bazelbuild/rules_nodejs#180]
When running bazel build on an angular project, you will encounter an issue with rollup:

```
ERROR: /home/kcannon/Development/cloud/redacted/src/packages/sockets/BUILD:16:1: Angular Packaging: rolling up npm_package failed (Exit 1)
[!] ReferenceError: bazel is not defined
ReferenceError: bazel is not defined
    at Object.<anonymous> (/home/kcannon/.cache/bazel/_bazel_kcannon/762094745a3d69d3835e2eb1e72a68b3/execroot/redacted/bazel-out/k8-fastbuild/bin/src/packages/sockets/_npm_package.rollup.conf.js:15:16)
    at Module._compile (module.js:635:30)
    at Object.require.extensions..js (/home/kcannon/.cache/bazel/_bazel_kcannon/762094745a3d69d3835e2eb1e72a68b3/external/build_bazel_rules_nodejs_rollup_deps/node_modules/rollup/bin/rollup:20371:8)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at rollup.rollup.then.then (/home/kcannon/.cache/bazel/_bazel_kcannon/762094745a3d69d3835e2eb1e72a68b3/external/build_bazel_rules_nodejs_rollup_deps/node_modules/rollup/bin/rollup:20378:27)
    at <anonymous>

```

```
// Rollup configuration
// GENERATED BY Bazel

const rollup = require('rollup');
const nodeResolve = require('rollup-plugin-node-resolve');
const path = require('path');
const fs = require('fs');

const DEBUG = false;

const moduleMappings = {"rxjs/ajax": "external/rxjs/ajax/index.d.ts", "rxjs/operators": "external/rxjs/operators/index.d.ts", "rxjs/testing": "external/rxjs/testing/index.d.ts", "rxjs/websocket": "external/rxjs/websocket/index.d.ts", "rxjs": "external/rxjs//index.d.ts", "@redacted/socets": "src/packages/sockets"};
const workspaceName = 'redacted';
const rootDirs = bazel-out/k8-fastbuild/bin/src/packages/sockets/npm_package.esm5;
const banner_file = "src/packages/license-banner.txt";
const stamp_data = "bazel-out/volatile-status.txt";

```

when looking at the code, I noticed that rootDirs isn't escaped
`const rootDirs = bazel-out/k8-fastbuild/bin/src/packages/sockets/npm_package.esm5;`

corresponding code blocks:

https://github.com/bazelbuild/rules_nodejs/blob/1931156c232a08356dfda02e9c8b0275c2e63c00/internal/rollup/rollup.config.js#L14

https://github.com/bazelbuild/rules_nodejs/blob/1931156c232a08356dfda02e9c8b0275c2e63c00/internal/rollup/rollup_bundle.bzl#L79

my guess is 
`const rootDirs = TMPL_rootDir;`
 needs to be
 `const rootDirs = 'TMPL_rootDir'`;

**Comment by alexeagle** [comment]
This was supposed to work because the TMPL_rootDir would have the value `"path/to/root"` - with the double quotes included in the value. This would make it appear with quotes in the resulting rollup config.

I don't understand the conditions where this works vs. where it doesn't. Is it platform-dependent maybe?

In any case your fix is more consistent with other variables we interpolate into the template, where the quotes live in the template file. Thanks!
