### ISSUE TITLE
build fails with ENOENT for a file that's not in my dependencies

### ISSUE THREAD

**Issue by ribrdb** [bazelbuild/rules_nodejs#1858]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 
ts_library

### Is this a regression?

I don't know. It seems to happen intermittently only on some machines. The version of rules_nodejs doesn't seem to matter. I've seen it with both 0.37.0 and 1.0.1

### Description

My build fails with this error:

```
ERROR: /home/ryan/myagent/_work/3/s/third_party/lit-html/BUILD:7:1: Compiling TypeScript (devmode) //third_party/lit-html:lit-html failed (Exit 1)
Error: ENOENT: no such file or directory, open '/home/ryan/.cache/bazel/_bazel_ryan/e89d946e58cdc4ed2275725cd7015ebd/execroot/derivita/third_party/lit-html/node_modules/@types/mocha/index.d.ts'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at UncachedFileLoader.loadFile (/home/ryan/.cache/bazel/_bazel_ryan/e89d946e58cdc4ed2275725cd7015ebd/execroot/derivita/bazel-out/host/bin/tools/typescript/tsc_wrapped.sh.runfiles/npm/node_modules/@bazel/typescript/internal/tsc_wrapped/cache.js:350:35)
    at /home/ryan/.cache/bazel/_bazel_ryan/e89d946e58cdc4ed2275725cd7015ebd/execroot/derivita/bazel-out/host/bin/tools/typescript/tsc_wrapped.sh.runfiles/npm/node_modules/@bazel/typescript/internal/tsc_wrapped/compiler_host.js:376:44
    at Object.wrap (/home/ryan/.cache/bazel/_bazel_ryan/e89d946e58cdc4ed2275725cd7015ebd/execroot/derivita/bazel-out/host/bin/tools/typescript/tsc_wrapped.sh.runfiles/npm/node_modules/@bazel/typescript/internal/tsc_wrapped/perf_trace.js:44:20)
    at CompilerHost.getSourceFile (/home/ryan/.cache/bazel/_bazel_ryan/e89d946e58cdc4ed2275725cd7015ebd/execroot/derivita/bazel-out/host/bin/tools/typescript/tsc_wrapped.sh.runfiles/npm/node_modules/@bazel/typescript/internal/tsc_wrapped/compiler_host.js:375:30)
    at findSourceFile (/home/ryan/.cache/bazel/_bazel_ryan/e89d946e58cdc4ed2275725cd7015ebd/execroot/derivita/bazel-out/host/bin/tools/typescript/tsc_wrapped.sh.runfiles/npm/node_modules/typescript/lib/typescript.js:96404:29)
    at /home/ryan/.cache/bazel/_bazel_ryan/e89d946e58cdc4ed2275725cd7015ebd/execroot/derivita/bazel-out/host/bin/tools/typescript/tsc_wrapped.sh.runfiles/npm/node_modules/typescript/lib/typescript.js:96287:85
    at getSourceFileFromReferenceWorker (/home/ryan/.cache/bazel/_bazel_ryan/e89d946e58cdc4ed2275725cd7015ebd/execroot/derivita/bazel-out/host/bin/tools/typescript/tsc_wrapped.sh.runfiles/npm/node_modules/typescript/lib/typescript.js:96254:34)
    at processSourceFile (/home/ryan/.cache/bazel/_bazel_ryan/e89d946e58cdc4ed2275725cd7015ebd/execroot/derivita/bazel-out/host/bin/tools/typescript/tsc_wrapped.sh.runfiles/npm/node_modules/typescript/lib/typescript.js:96287:13)
ERROR: /home/ryan/myagent/_work/3/s/omaha/BUILD:171:1 Compiling TypeScript (devmode) //third_party/lit-html:lit-html failed (Exit 1)
```

However I have no idea why it thinks that file should exist.
It's not referenced by any files being compiled. There are other files in the source directory that reference it via /// directives, but they are not included into any ts_library.

If I delete the comments from those files, the build works. But I'm not compiling those files so they shouldn't affect the build. I've confirmed with bazel query and by looking at the generated tsconfig.json that those files are not somehow getting included in the compilation.

Also this only seems to happen on our continuous build machine, but not when run locally. I don't have any clue what's different.
## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 18.04.4 LTS
  </code>
</pre>

**Output of `bazel version`:**

<pre>c
  <code>
Bazelisk version: v1.4.0
Starting local Bazel server and connecting to it...
Build label: 3.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Apr 22 10:32:27 2020 (1587551547)
Build timestamp: 1587551547
Build timestamp as int: 1587551547

  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
1.0.1
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
TypeScript by default includes all `node_modules/@types` it can find in the program, whether you request them or not. That's how magical ambient typings happen to resolve.

I prefer to set `types: []` in the tsconfig to disable that magic. If you do need some `@types` you can add them, or even better use `/// <reference types="thing"/>` so the dependency comes from the usage site.

It's probably intermittent for you because it depends on whether TypeScript hopped outside the sandbox by following symlinks, and whether the tsc_wrapped CompilerHost was able to lie about the existence of the file.

note that newer rules_nodejs have a --require script that masks the symlinks in the execroot so they appear as regular files, which helps prevent tools like typescript from looking around the rest of your disk and breaking hermeticity in this way.

**Comment by ribrdb** [comment]
I don't think this is exactly what's going on.
@types/mocha isn't in my node_modules anywhere.
I have a ts_library in third_party/lit-html:
```
ts_library(
    name = "lit-html",
    srcs = glob([
        "src/*.ts",
        "src/lib/*.ts",
        "src/directives/*.ts",
    ]),
    tsconfig = "tsconfig.json",
)
```

There are files in third_party/lit-html/src/test/, which are not referenced by any build file, that contain:
`/// <reference path="../../../node_modules/@types/mocha/index.d.ts" />`
The presence of this comment is breaking my build.
If I delete this comment from the files under src/test, the build succeeds.
