### ISSUE TITLE
ts_library does not find @bazel/typescript/bin/tsc_wrapped.sh on windows

### ISSUE THREAD

**Issue by Socolin** [bazelbuild/rules_nodejs#1880]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: 
```
ts_library(
    name = "src",
    srcs = glob(include = [
        "**/*.ts",
    ], exclude = [
        "index.ts"
    ]),
    tsconfig = "//:tsconfig.json"
)
```

### Description

When building on **Windows 10** it does not seems to find the file tsc_wrapped.sh

## 🔬 Minimal Reproduction

https://github.com/Socolin/ReproBugBazelTscWrapped

```
PS D:\temp> git clone git@github.com:Socolin/ReproBugBazelTscWrapped.git
PS D:\temp\ReproBugBazelTscWrapped> bazel build src:src
Starting local Bazel server and connecting to it...
INFO: Analyzed target //src:src (47 packages loaded, 746 targets configured).
INFO: Found 1 target...
ERROR: D:/temp/reprobugbazeltscwrapped/src/BUILD.bazel:8:1: Compiling TypeScript (devmode) //src:src failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at C:/users/some-user/_bazel_some-user/rtzg7pnr/bazel-workers/worker-0-TypeScriptCompile.log ---8<---8<---
/bin/bash: C:/users/some-user/_bazel_some-user/rtzg7pnr/execroot/shared/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.sh: No such file or directory
---8<---8<--- End of log ---8<---8<---
Target //src:src failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 11.861s, Critical Path: 0.35s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

## 🔥 Exception or Error

<pre><code>
---8<---8<--- Start of log, file at C:/users/some-user/_bazel_some-user/rtzg7pnr/bazel-workers/worker-0-TypeScriptCompile.log ---8<---8<---
/bin/bash: C:/users/some-user/_bazel_some-user/rtzg7pnr/execroot/shared/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.sh: No such file or directory
---8<---8<--- End of log ---8<---8<---
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows 10
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 3.1.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Apr 22 10:35:28 2020 (1587551728)
Build timestamp: 1587551728
Build timestamp as int: 1587551728
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
      1.6.1
  </code>
</pre>

**Anything else relevant?**

It works on linux.

Here are the files available in `@bazel/typescript/bin/` files.

```
    Directory: C:\users\some-user\_bazel_some-user\rtzg7pnr\execroot\shared\bazel-out\host\bin\external\npm\@bazel\typescript\bin


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        5/10/2020   6:09 PM                tsc_wrapped.bat.runfiles
-ar---        5/10/2020   6:09 PM           1644 tsc_wrapped.bat
-ar---        5/10/2020   6:09 PM         242522 tsc_wrapped.bat.runfiles_manifest
-ar---        5/10/2020   6:09 PM          12007 tsc_wrapped.sh
-ar---        5/10/2020   6:09 PM           1429 tsc_wrapped_loader.js
-ar---        5/10/2020   6:09 PM          19082 tsc_wrapped_require_patch.js
-ar---        5/10/2020   6:09 PM            139 _tsc_wrapped.module_mappings.json
```

**Comment by Socolin** [comment]
So I think I found the problem.

It's trying to execute a bash script here:
https://github.com/bazelbuild/rules_nodejs/blob/master/internal/common/windows_utils.bzl#L105

But it's trying to execute bash.exe from WSL instead of executing bash.exe from cygwin.
If I change my PATH, to move `C:\cygwin64\bin` before `system32` and it's working.

**Comment by Socolin** [comment]
Now I have another problem, when executing jest with bazel, I get this error

```
Executing tests from //tests:test
-----------------------------------------------------------------------------
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat 'C:\cygdrive'
    at Object.realpathSync (fs.js:1529:7)
    at Object.exports.patcher [as fs] (C:\users\bertrand.provost\_bazel_bertrand.provost\u3lrkeg4\external\build_bazel_rules_nodejs\internal\node\node_patches.js:74:15)
    at Object.<anonymous> (C:\users\bertrand.provost\_bazel_bertrand.provost\u3lrkeg4\external\build_bazel_rules_nodejs\internal\node\node_patches.js:666:9)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1125:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:443:5) {
  errno: -4058,
  syscall: 'lstat',
  code: 'ENOENT',
  path: 'C:\\cygdrive'
}
```

I'm gonna dig this later.

**Comment by Socolin** [comment]
I was able to go a bit further by creating a directory `cygdrive` then adding a link like this: `mklink /j c:\cygdrive\c C:\` but then I get another error

For repro, you can use the jest example from this repository

https://github.com/bazelbuild/rules_nodejs/tree/master/examples/jest


```
> bazel.exe test test
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 36333028-14a7-4697-98ee-47dda2a22ad4
yarn install v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "win32" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ patch-package
patch-package 6.2.0
Applying patches...
jest-haste-map@24.9.0 Γ£ö
Done in 12.92s.
INFO: Analyzed target //:test (503 packages loaded, 10582 targets configured).
INFO: Found 1 test target...
FAIL: //:test (see C:/users/some-user/_bazel_some-user/olmlednd/execroot/examples_jest/bazel-out/x64_windows-fastbuild/testlogs/test/test.log)
INFO: From Testing //:test:
==================== Test output for //:test:
Error: Can't find a root directory while resolving a config file path.
Provided path to resolve: ./jest.config.js
cwd: C:\users\some-user\_bazel_some-user\olmlednd\execroot\examples_jest\bazel-out\x64_windows-fastbuild\bin\test.bat.runfiles\examples_jest
    at _default (C:\users\some-user\_bazel_some-user\olmlednd\execroot\examples_jest\node_modules\jest-config\build\resolveConfigPath.js:69:11)
    at readConfig (C:\users\some-user\_bazel_some-user\olmlednd\execroot\examples_jest\node_modules\jest-config\build\index.js:152:49)
    at readConfigs (C:\users\some-user\_bazel_some-user\olmlednd\execroot\examples_jest\node_modules\jest-config\build\index.js:373:26)
    at C:\users\some-user\_bazel_some-user\olmlednd\execroot\examples_jest\node_modules\jest-cli\node_modules\@jest\core\build\cli\index.js:155:58
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\users\some-user\_bazel_some-user\olmlednd\execroot\examples_jest\node_modules\jest-cli\node_modules\@jest\core\build\cli\index.js:108:24)
    at _next (C:\users\some-user\_bazel_some-user\olmlednd\execroot\examples_jest\node_modules\jest-cli\node_modules\@jest\core\build\cli\index.js:128:9)
    at C:\users\some-user\_bazel_some-user\olmlednd\execroot\examples_jest\node_modules\jest-cli\node_modules\@jest\core\build\cli\index.js:133:7
    at new Promise (<anonymous>)
    at C:\users\some-user\_bazel_some-user\olmlednd\execroot\examples_jest\node_modules\jest-cli\node_modules\@jest\core\build\cli\index.js:125:12
================================================================================
Target //:test up-to-date:
  dist/bin/test.sh
  dist/bin/test_loader.js
  dist/bin/test_require_patch.js
  dist/bin/test.bat
INFO: Elapsed time: 47.876s, Critical Path: 9.90s
INFO: 2 processes: 2 local.
INFO: Build completed, 1 test FAILED, 9 total actions
//:test                                                                  FAILED in 9.3s
  C:/users/some-user/_bazel_some-user/olmlednd/execroot/examples_jest/bazel-out/x64_windows-fastbuild/testlogs/test/test.log

INFO: Build completed, 1 test FAILED, 9 total actions
```

At this point I have no clue about what to do to go further, any help would be very welcome.

**Comment by Socolin** [comment]
So I finally found a solution. It seems to works using `bash.exe` from git bash (git for windows)

I defined this path in `BAZEL_SH` env variable so bazel use it before trying to find another bash.exe in PATH.

I'm closing this issue since problem is also reported here.

https://github.com/bazelbuild/bazel/issues/10941
