### ISSUE TITLE
ts_proto_library: Cannot depend on external proto_library

### ISSUE THREAD

**Issue by gonzojive** [bazelbuild/rules_nodejs#1946]
# 🐞 bug report

### Affected Rule

ts_proto_library (grpc version in the labs project)

### Is this a regression?

No. I don't think this feature was ever supported.

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

This works:
```shell
git clone https://github.com/gonzojive/ts_proto_help.git
cd original_example
bazel test //...
```

This folder is the same but has a dependency on "google/type/latlng.proto":

```shell
git clone https://github.com/gonzojive/ts_proto_help.git
cd updated_example
bazel build //:car_proto
# INFO: Build completed successfully, 1 total action
bazel test //...
# fails with below error
```

## 🔥 Exception or Error

```
$ bazel test //...
INFO: Build option --define has changed, discarding analysis cache.
INFO: Analyzed 24 targets (0 packages loaded, 10430 targets configured).
INFO: Found 19 targets and 5 test targets...
ERROR: /home/red/git/demos/ts_proto_help/updated_example/BUILD.bazel:86:1: Bundling JavaScript bundle.js [rollup] failed (Exit 1) rollup.sh failed: error executing command bazel-out/host/bin/external/npm/rollup/bin/rollup.sh bazel-out/k8-fastbuild/bin/app.mjs --output.file bazel-out/k8-fastbuild/bin/bundle.js --format iife --config ... (remaining 6 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox

bazel-out/k8-fastbuild/bin/app.mjs → bazel-out/k8-fastbuild/bin/bundle.js...
[!] Error: Could not resolve './google/type/latlng_pb' from node_modules/updated_example_ws/car_pb.mjs
Error: Could not resolve './google/type/latlng_pb' from node_modules/updated_example_ws/car_pb.mjs
    at error (/home/red/.cache/bazel/_bazel_red/ec4cc2e04810cf9c9e7fbb006efc9622/sandbox/linux-sandbox/525/execroot/updated_example_ws/node_modules/rollup/dist/rollup.js:9419:30)
    at ModuleLoader.handleMissingImports (/home/red/.cache/bazel/_bazel_red/ec4cc2e04810cf9c9e7fbb006efc9622/sandbox/linux-sandbox/525/execroot/updated_example_ws/node_modules/rollup/dist/rollup.js:16467:17)
    at ModuleLoader.<anonymous> (/home/red/.cache/bazel/_bazel_red/ec4cc2e04810cf9c9e7fbb006efc9622/sandbox/linux-sandbox/525/execroot/updated_example_ws/node_modules/rollup/dist/rollup.js:16518:26)
    at Generator.next (<anonymous>)
    at fulfilled (/home/red/.cache/bazel/_bazel_red/ec4cc2e04810cf9c9e7fbb006efc9622/sandbox/linux-sandbox/525/execroot/updated_example_ws/node_modules/rollup/dist/rollup.js:40:28)

INFO: Elapsed time: 1.995s, Critical Path: 1.30s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
//:dummy_test                                                   (cached) PASSED in 0.1s
//:devserver_test_chromium-local                                      NO STATUS
//:prodserver_test_chromium-local                                     NO STATUS
//:test_chromium-local                                                NO STATUS
//:test_firefox-local                                                 NO STATUS

Executed 0 out of 5 tests: 1 test passes and 4 were skipped.
FAILED: Build did NOT complete successfully
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
   Ubuntu 18.04
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 3.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Apr 22 10:32:27 2020 (1587551547)
Build timestamp: 1587551547
Build timestamp as int: 1587551547
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "84abf7ac4234a70924628baa9a73a5a5cbad944c4358cf9abdb4aab29c9a5b77",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/1.7.0/rules_nodejs-1.7.0.tar.gz"],
)
  </code>
</pre>

**Anything else relevant?**

https://github.com/gonzojive/ts_proto_help has an altered version of ts_proto_library that I'm using to fix issues from the labs version. You can toggle it on and off in the BUILD.bazel file:

```skylark
load("@npm_bazel_labs//:index.bzl", "ts_proto_library")
#load("@updated_example_ws//updated_rules:ts_proto_library_fix.bzl", "ts_proto_library")
```

One issue with the current ts_proto_library is that `_build_protoc_command` uses `ctx.var["BINDIR"]` as the output directory passed to protoc. This is not correct for external repositories, which will typically output to `bazel-bin/external/<repo name>/<path to input proto?>{_pb.js,...}`. This results in the wrong input and output path being passed into the `change_import_style` binary.

`change_import_style` also has a bug in that it tolerates nonexistent input files. This is not appropriate for the non-gRPC `_pb.js` file that is generated for each input proto, which should always be created by protoc afaict. I think this bug is responsible for confusing behavior in other open issues where generated proto libraries contain no exports.

Two further stumbling blocks that make it unclear how to fix:

1. I'm not quite sure how one is supposed to import ts_library rules declared in non-npm external repositories.  This isn't documented in the [ts_library docs](https://bazelbuild.github.io/rules_nodejs/TypeScript.html). The docs say that imports to ts_libraries defined in the workspace can be done by prefixing the name of the workspace.

2. How should one import an external proto in a `.ts` file if there is no `ts_proto_library` for that proto?

**Comment by alexeagle** [comment]
Cc @mrmeku

**Comment by gonzojive** [comment]
Please see https://github.com/gonzojive/ts_proto_help/blob/master/updated_example/updated_rules/ts_proto_library_fix.bzl and https://github.com/gonzojive/ts_proto_help/blob/master/updated_example/updated_rules/change_import_style.js for changes to the labs implementation. It's WIP, and I'll send a pull request if I have a chance to get the changes into better shape.

**Comment by gonzojive** [comment]
Still a problem, please keep open.

**Comment by bshimc** [comment]
xref https://github.com/protocolbuffers/protobuf/issues/5318

**Comment by gonzojive** [comment]
I have worked around some of these problems by wrapping protoc in a binary that allows specifying the destination paths explicitly. It involves changes to `ts_proto_library.bzl` and a new Go program like this:

```go
// Program protoc_wrap calls protoc and then moves the output files to a destination directory.
//
// This program exists becuase the protoc JS plugin doesn't support extensive options for configuring the output destination:
// https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/js/js_generator.cc
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io/ioutil"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"github.com/bazelbuild/rules_go/go/tools/bazel"
	"github.com/golang/glog"
)

var (
	protocPath = flag.String("protoc", "", "Path to the protoc binary. If empty, searches the bazel runfiles directory.")
	plugin     = flag.String("plugin", "", "protoc --plugin flag")
	// grpcWebOut      = flag.String("grpc-web_out", "", "protoc --grpc-web_out flag")
	//jsOut           = flag.String("js_out", "", "protoc --js_out flag")
	descriptorSetIn = flag.String("descriptor_set_in", "", "protoc --descriptor_set_in flag")
	sourceFile      = flag.String("input_proto", "", "input .proto file")
	importPath      = flag.String("import_path", "", "The protobuf import path of the input proto file.")

	mappingJSON = flag.String("mapping", "", "JSON encoded mapping of inputs to outputs.")
)

func main() {
	flag.Parse()
	if err := run(context.Background()); err != nil {
		glog.Exitf("error running protoc_wrap: %v", err)
	}
}

func run(ctx context.Context) error {
	protoc := *protocPath
	if protoc == "" {
		p, err := bazel.Runfile("protoc")
		if err != nil {
			return fmt.Errorf("could not determine protoc from runfile deps: %w", err)
		}
		protoc = p
	}

	tmpDir, err := ioutil.TempDir(os.TempDir(), "protoc_output")
	if err != nil {
		return err
	}
	glog.Infof("outputting stuff to %q", tmpDir)
	defer os.RemoveAll(tmpDir)

	m := &mapping{}
	if err := json.Unmarshal([]byte(*mappingJSON), m); err != nil {
		return fmt.Errorf("could not parse JSON mapping: %w; input: %q", err, *mappingJSON)
	}

	grpcWebOut := fmt.Sprintf("import_style=commonjs+dts,mode=grpcweb:%s", tmpDir)
	jsOut := fmt.Sprintf("import_style=commonjs:%s", tmpDir)

	args := []string{
		"--plugin", *plugin,
		"--grpc-web_out", grpcWebOut,
		"--js_out", jsOut,
		"--descriptor_set_in", *descriptorSetIn,
	}
	args = append(args, m.protos()...)

	cmd := exec.CommandContext(ctx, protoc, args...)
	if cmd.Stderr != nil {
		return fmt.Errorf("cmd sets stderr accidentally")
	}
	glog.Infof("executing command %s", cmd)
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("error running protoc: %w // output: %s", err, output)
	}
	filepath.Walk(tmpDir, func(path string, info os.FileInfo, err error) error {
		glog.Infof("walked output file %q", path)
		return nil
	})
	for _, e := range m.Entries {
		if err := e.moveFile(ctx, tmpDir); err != nil {
			return err
		}
	}
	return nil
}

type mapping struct {
	Entries []*mappingEntry `json:"specs"`
}

func (m *mapping) protos() []string {
	protos := map[string]bool{}
	strs := []string{}
	for _, e := range m.Entries {
		inputProto := e.ImportPath
		if protos[inputProto] {
			continue
		}
		protos[inputProto] = true
		strs = append(strs, inputProto)
	}
	sort.Strings(strs)
	return strs
}

type mappingEntry struct {
	InputProto string `json:"input_proto"`
	ImportPath string `json:"import_path"`
	OutputPath string `json:"output_path"`
	Type       string `json:"type"`
}

func (e *mappingEntry) outputBaseName() string {
	withoutExt := strings.TrimSuffix(path.Base(e.ImportPath), ".proto")
	switch e.Type {
	case "js":
		return fmt.Sprintf("%s_pb.js", withoutExt)
	case "js_types":
		return fmt.Sprintf("%s_pb.d.ts", withoutExt)
		// TODO(reddaly): Consider adding back cases for grpc
		// case "grpc":
		// 	return fmt.Sprintf("%s_grpc_web_pb.js", withoutExt)
		// case "grpc_types":
		// 	return fmt.Sprintf("%s_grpc_web_pb.d.ts", withoutExt)
	}
	return withoutExt
}

// moveFile moves the output of protoc to the specified output path.
func (e *mappingEntry) moveFile(ctx context.Context, tmpDir string) error {
	inputPath := path.Join(tmpDir, path.Dir(e.ImportPath), e.outputBaseName())
	contents, err := ioutil.ReadFile(inputPath)
	if err != nil {
		return fmt.Errorf("error reading expected output file for %q/%q: file = %q, err = %w", e.ImportPath, e.Type, inputPath, err)
	}
	if err := ioutil.WriteFile(e.OutputPath, contents, 0664); err != nil {
		return fmt.Errorf("error writing output file for %q/%q: %w", e.ImportPath, e.Type, err)
	}
	return nil
}
```

**Comment by gonzojive** [comment]
I have worked around this by modifying the proto rules, but maybe somebody
has an official solution.
