### ISSUE TITLE
tsc does not work with sandboxfs, getting EACCES when trying to link node_modules

### ISSUE THREAD

**Issue by hristozov** [bazelbuild/rules_nodejs#1982]
# 🐞 bug report

### Affected Rule

`tsc`

### Is this a regression?

Not sure, probably not.

### Description

Invoking the TS compiler (`tsc`) doesn't seem to work correctly with [sandboxfs](https://github.com/bazelbuild/sandboxfs). `link_node_modules.js` seems to get an `EACCES` when preparing the symlinks, probably due to the fact that the execroot is read-only in the sandboxfs world.

This might affect other rules relying on the script.

## 🔬 Minimal Reproduction

Repository: https://github.com/hristozov/tsc-error-repro

* `bazel run //:test_binary` prints `hello`, as expected
* `bazel run //:test_binary --experimental_use_sandboxfs=true` causes an error, see below 💥

(You need to have the sandboxfs FUSE module installed. You might also need to set `--experimental_sandboxfs_path` to the binary)

## 🔥 Exception or Error

<pre><code>
$ bazel run //:test_binary --experimental_use_sandboxfs=true --define=VERBOSE_LOGS=1 --sandbox_debug
INFO: Build option --define has changed, discarding analysis cache.
DEBUG: /private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/external/build_bazel_rules_nodejs/internal/common/module_mappings.bzl:41:14: [module_mappings.bzl] Mappings at @npm//typescript:typescript__nested_node_modules: {}
DEBUG: /private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//typescript:typescript__nested_node_modules
DEBUG: /private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/external/build_bazel_rules_nodejs/internal/common/module_mappings.bzl:41:14: [module_mappings.bzl] Mappings at @npm//typescript:typescript__files: {}
DEBUG: /private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//typescript:typescript__files
DEBUG: /private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/external/build_bazel_rules_nodejs/internal/common/module_mappings.bzl:41:14: [module_mappings.bzl] Mappings at @npm//typescript:typescript__contents: {}
DEBUG: /private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//typescript:typescript__contents
DEBUG: /private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//typescript:typescript
DEBUG: /private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/external/build_bazel_rules_nodejs/internal/common/module_mappings.bzl:41:14: [module_mappings.bzl] Mappings at @npm//typescript:typescript: {}
DEBUG: /private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for //:test_target
DEBUG: /private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/external/build_bazel_rules_nodejs/internal/common/module_mappings.bzl:41:14: [module_mappings.bzl] Mappings at //:test_target: {}
INFO: Analyzed target //:test_binary (0 packages loaded, 224 targets configured).
INFO: Found 1 target...
INFO: Unmounting sandboxfs instance left behind on /private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/sandbox/sandboxfs by a previous command
INFO: Mounting sandboxfs instance on /private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/sandbox/sandboxfs
ERROR: /Users/ghristozov/src/tsc-error-repro/BUILD.bazel:4:4: Action 1.js failed (Exit 1) sandbox-exec failed: error executing command
  (cd /private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/sandbox/sandboxfs/5/__main__ && \
  exec env - \
    BAZEL_NODE_MODULES_ROOT='' \
    COMPILATION_MODE=fastbuild \
    TMPDIR=/var/folders/kg/bhb4b57935l0l9j7m18kl2h800bghj/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/sandbox/darwin-sandbox/8/sandbox.sb /var/tmp/_bazel_ghristozov/install/61db5d53585987231f4d53a8cabb67b1/process-wrapper '--timeout=0' '--kill_delay=15' bazel-out/host/bin/external/npm/typescript/bin/tsc.sh --outDir bazel-out/darwin-fastbuild/bin --lib es2017,dom --downlevelIteration --declaration ./1.ts '--bazel_node_modules_manifest=bazel-out/darwin-fastbuild/bin/_test_target.module_mappings.json' --nobazel_patch_module_resolver)
[link_node_modules.js] manifest file bazel-out/darwin-fastbuild/bin/_test_target.module_mappings.json
[link_node_modules.js] manifest contents {
  "workspace": "__main__",
  "bin": "bazel-out/darwin-fastbuild/bin",
  "root": "npm/node_modules",
  "modules": {
    "__main__": [
      "execroot",
      "bazel-out/darwin-fastbuild/bin"
    ]
  }
}
[link_node_modules.js] startCwd /private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/sandbox/sandboxfs/5/__main__
[link_node_modules.js] isExecroot true
[link_node_modules.js] resolved node_modules root npm/node_modules to /private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/sandbox/sandboxfs/5/__main__/external/npm/node_modules
[link_node_modules.js] cwd /private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/sandbox/sandboxfs/5/__main__
(node:59168) ExperimentalWarning: The fs.promises API is experimental
[link_node_modules.js] symlink( node_modules -> /private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/sandbox/sandboxfs/5/__main__/external/npm/node_modules )
[link_node_modules.js] mapping hierarchy [{"name":"__main__","link":["execroot","bazel-out/darwin-fastbuild/bin"]}]
[link_node_modules.js] symlink( __main__ -> /private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/sandbox/sandboxfs/5/__main__/bazel-out/darwin-fastbuild/bin )
[link_node_modules.js] { [Error: EACCES: permission denied, symlink '/private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/sandbox/sandboxfs/5/__main__/bazel-out/darwin-fastbuild/bin' -> '__main__']
  errno: -13,
  code: 'EACCES',
  syscall: 'symlink',
  path:
   '/private/var/tmp/_bazel_ghristozov/e18a944ed235b5dc42cc311549e940fc/sandbox/sandboxfs/5/__main__/bazel-out/darwin-fastbuild/bin',
  dest: '__main__' }
Target //:test_binary failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Leaving sandboxfs mounted because of --sandbox_debug
INFO: Elapsed time: 0.728s, Critical Path: 0.45s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS 10.14.6
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 3.3.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jun 18 02:55:10 2020 (1592448910)
Build timestamp: 1592448910
Build timestamp as int: 1592448910
  </code>
</pre>

**Rules_nodejs version:**

<pre>
  <code>
1.7.0
  </code>
</pre>

**Anything else relevant?**

**Comment by hristozov** [comment]
FWIW, there are similar sandboxfs issues with the examples, on `master`:

```
$ git log -n1
* 17c02445 - (HEAD -> master, origin/master, origin/HEAD) chore: vue example cleanup and add trivial test target (21 hours ago) <Alex Eagle>
$ cd examples/angular_bazel_architect
$ bazel build '...' --experimental_use_sandboxfs=true
INFO: Invocation ID: eb9e574f-5ac2-49ec-813f-f77e15fb8385
INFO: Build option --define has changed, discarding analysis cache.
INFO: Analyzed 9 targets (0 packages loaded, 79584 targets configured).
INFO: Found 9 targets...
ERROR: /Users/ghristozov/src/mirrors_github_rules_nodejs/examples/angular_bazel_architect/projects/frontend-lib/BUILD.bazel:6:10: Action projects/frontend-lib/build failed (Exit 1) architect.sh failed: error executing command bazel-out/host/bin/external/npm/@angular-devkit/architect-cli/bin/architect.sh frontend-lib:build -- bazel-out/darwin-fastbuild/bin/projects/frontend-lib/build ... (remaining 2 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/private/var/tmp/_bazel_ghristozov/8a0226209302962a4ba1699a719b83aa/sandbox/sandboxfs/2/angular_bazel_architect/bazel-out/host/bin/external/npm/@angular-devkit/architect-cli/bin/architect.sh.runfiles/build_bazel_rules_nodejs/internal/node/node_patches.js:567
                throw e;
                ^

Error: ENOENT: no such file or directory, mkdir '/private/var/tmp/_bazel_ghristozov/8a0226209302962a4ba1699a719b83aa/sandbox/sandboxfs/2/angular_bazel_architect/bazel-out/host/bin/external/npm/@angular-devkit/architect-cli/bin/architect.sh.runfiles/build_bazel_rules_nodejs/internal/node/_node_bin'
    at Object.mkdirSync (fs.js:823:3)
    at Object.exports.patcher [as subprocess] (/private/var/tmp/_bazel_ghristozov/8a0226209302962a4ba1699a719b83aa/sandbox/sandboxfs/2/angular_bazel_architect/bazel-out/host/bin/external/npm/@angular-devkit/architect-cli/bin/architect.sh.runfiles/build_bazel_rules_nodejs/internal/node/node_patches.js:562:18)
    at Object.<anonymous> (/private/var/tmp/_bazel_ghristozov/8a0226209302962a4ba1699a719b83aa/sandbox/sandboxfs/2/angular_bazel_architect/bazel-out/host/bin/external/npm/@angular-devkit/architect-cli/bin/architect.sh.runfiles/build_bazel_rules_nodejs/internal/node/node_patches.js:674:5)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1125:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:443:5) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/private/var/tmp/_bazel_ghristozov/8a0226209302962a4ba1699a719b83aa/sandbox/sandboxfs/2/angular_bazel_architect/bazel-out/host/bin/external/npm/@angular-devkit/architect-cli/bin/architect.sh.runfiles/build_bazel_rules_nodejs/internal/node/_node_bin'
}
INFO: Elapsed time: 6.958s, Critical Path: 2.75s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

Verbose output can be found [here](https://gist.githubusercontent.com/hristozov/a2fdab9eeeac1411b82769dae3af1433/raw/bb09917402104a1e5ca5dd62cffdbc73d49485f9/output.txt).
