### ISSUE TITLE
Combining tsx with sass_library

### ISSUE THREAD

**Issue by cjds** [bazelbuild/rules_nodejs#2172]
I'm trying to reference the output of a SASS library in a typescript program but it doesn't work

### Relevant Rules

This is the BUILD.bazel file
```
package(default_visibility = ["//visibility:public"])
load("@npm//@bazel/typescript:index.bzl", "ts_library")
load("@io_bazel_rules_sass//:defs.bzl", "sass_binary")

sass_binary(
    name = "styles",
    src = "AppBar.scss",
)

ts_library(
    name = "AppBar",
    srcs = [
        "AppBar.tsx",
    ],
    deps = [
        "@npm//@types/react",
        "@npm//@types/react-dom",
       ":styles",
    ],
    data = [
    ],
)

```

This is the error I get

```
ERROR: /rpicar/ui/components/AppBar/BUILD.bazel:10:11: in ts_library rule //ui/components/AppBar:AppBar: 
Traceback (most recent call last):
        File "/rpicar/ui/components/AppBar/BUILD.bazel", line 10
                ts_library(name = 'AppBar')
        File "/root/.cache/bazel/_bazel_root/a24326a56432a033218a21510efea07d/external/npm/@bazel/typescript/internal/build_defs.bzl", line 305, in _ts_library_impl
                compile_ts(ctx, <4 more arguments>)
        File "/root/.cache/bazel/_bazel_root/a24326a56432a033218a21510efea07d/external/npm/@bazel/typescript/internal/common/compilation.bzl", line 220, in compile_ts
                d[DeclarationInfo]
<merged target //ui/components/AppBar:styles> doesn't contain declared provider 'DeclarationInfo'
ERROR: Analysis of target '//ui/components/AppBar:AppBar' failed; build aborted: Analysis of target '//ui/components/AppBar:AppBar' failed
INFO: Elapsed time: 0.137s
INFO: 0 processes.

```

This is how I'm using it in Typescript

```
import React from "react";
import styles from "./AppBar.css";

console.log(styles);

export const AppBar = () => {
  return (
    <div className={styles["app-bar"]}>
      <h1>app bar</h1>
    </div>
  );
};
```

**Comment by mattem** [comment]
I'm not too familiar with React in particular, but I'd imagine that it's the job of the bundler to bundle the css, rather than the Typescript compiler, so I don't think there would be a dependency between a `sass_binary` and a `ts_library`.

A `ts_library#deps` attr can only depend on other rules that produce the `DeclarationInfo` provider (something that also outputs `d.ts` files).
 
I'd imagine you'd need an ambient type to declare the `*.css` module, something like:

```
declare module "*.css" {
  let _module: { [key: string]: string };
  export = _module;
}
```

The `BUILD` file would end up with something like, which is loosely based off the [example here](https://github.com/bazelbuild/rules_nodejs/tree/stable/examples/react_webpack)

```
load("@npm//@bazel/typescript:index.bzl", "ts_library")
load("@npm//http-server:index.bzl", "http_server")
load("@npm//webpack-cli:index.bzl", webpack = "webpack_cli")
load("@io_bazel_rules_sass//:defs.bzl", "sass_binary")

ts_library(
    name = "types",
    # ambient css module type declared in here
    srcs = ["types.d.ts"],
)

ts_library(
    name = "ts",
    srcs = [
        "AppBar.tsx",
    ],
    deps = [
        ":types",
        "@npm//react",
        "@npm//react-dom",
        "@npm//@types/react",
        "@npm//@types/react-dom",
    ],
    devmode_module = "esnext",
)

filegroup(
    name = "es_sources",
    srcs = [":ts"],
    output_group = "es5_sources",
)

sass_binary(
    name = "styles",
    src = "AppBar.scss",
)

webpack(
    name = "bundle",
    outs = ["app.bundle.js"],
    args = [
        "$(execpath :es_sources)",
        "--config",
        "$(execpath webpack.config.js)",
        "-o",
        "$@",
    ],
    data = [
        ":es_sources",
        "styles.css",
        "webpack.config.js",
        "@npm//:node_modules",
    ],
)

http_server(
    name = "server",
    data = [
        "app.bundle.js",
        "index.html",
    ],
    templated_args = ["."],
)
```

In this case, `bazel run //:server` would build and serve the app.

**Comment by alexeagle** [comment]
Right, a react app generally has a .d.ts file declaring the shapes of all css modules, so the type checker doesn't actually need to see the .css inputs

**Comment by cjds** [comment]
I see
