### ISSUE TITLE
Angular Architect Example Test Error: "No binary for ChromeHeadless browser on your platform" on Linux

### ISSUE THREAD

**Issue by flolu** [bazelbuild/rules_nodejs#2217]
# 🐞 bug report

### Affected example

[angular_bazel_architect](https://github.com/bazelbuild/rules_nodejs/tree/stable/examples/angular_bazel_architect)

## 🔬 Minimal Reproduction

I've just cloned the rules_nodejs repo and ran `yarn test` in the `examples/angular_bazel_architect` directory.

## 🔥 Exception or Error

```
$ bazel test :test
INFO: Invocation ID: 1c256086-7bd4-4ad7-95ab-c05cd153ba23
INFO: Analyzed target //:test (1068 packages loaded, 83846 targets configured).
INFO: Found 1 test target...
INFO: From Action projects/frontend-lib/build:

Browserslist: caniuse-lite is outdated. Please run the following command: `npm update`
Browserslist: caniuse-lite is outdated. Please run the following command: `npm update`
Building Angular Package
******************************************************************************
It is not recommended to publish Ivy libraries to NPM repositories.
Read more here: https://v9.angular.io/guide/ivy#maintaining-library-compatibility
******************************************************************************

------------------------------------------------------------------------------
Building entry point 'frontend-lib'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to UMD
Minifying UMD bundle
Writing package metadata
Built frontend-lib

------------------------------------------------------------------------------
Built Angular Package
 - from: /home/flolu/.cache/bazel/_bazel_flolu/ddcd1a310aa566a66906af93db7e118b/sandbox/linux-sandbox/1/execroot/angular_bazel_architect/projects/frontend-lib
 - to:   /home/flolu/.cache/bazel/_bazel_flolu/ddcd1a310aa566a66906af93db7e118b/sandbox/linux-sandbox/1/execroot/angular_bazel_architect/bazel-out/k8-fastbuild/bin/projects/frontend-lib/build
------------------------------------------------------------------------------
SUCCESS
Result: {
    "success": true,
    "target": {
        "project": "frontend-lib",
        "target": "build"
    }
}

Logs:

FAIL: //:test (see /home/flolu/.cache/bazel/_bazel_flolu/ddcd1a310aa566a66906af93db7e118b/execroot/angular_bazel_architect/bazel-out/k8-fastbuild/testlogs/test/test.log)
INFO: From Testing //:test:
==================== Test output for //:test:

18 10 2020 16:49:10.392:INFO [karma-server]: Karma v5.0.9 server started at http://0.0.0.0:9876/
18 10 2020 16:49:10.393:INFO [launcher]: Launching browsers ChromeHeadlessNoSandbox with concurrency unlimited
18 10 2020 16:49:10.395:INFO [launcher]: Starting browser ChromeHeadless
18 10 2020 16:49:10.396:ERROR [launcher]: No binary for ChromeHeadless browser on your platform.
  Please, set "CHROME_BIN" env variable.
FAILURE
Result: {
    "success": false,
    "target": {
        "project": "frontend",
        "target": "test"
    }
}

Logs:
Exiting with code  1 Error
    at process.exit (/home/flolu/.cache/bazel/_bazel_flolu/ddcd1a310aa566a66906af93db7e118b/sandbox/linux-sandbox/5/execroot/angular_bazel_architect/bazel-out/k8-fastbuild/bin/test.sh.runfiles/npm/node_modules/@angular-devkit/architect-cli/bin/architect.js:76:55)
    at /home/flolu/.cache/bazel/_bazel_flolu/ddcd1a310aa566a66906af93db7e118b/sandbox/linux-sandbox/5/execroot/angular_bazel_architect/bazel-out/k8-fastbuild/bin/test.sh.runfiles/npm/node_modules/@angular-devkit/architect-cli/bin/architect.js:167:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
================================================================================
Target //:test up-to-date:
  dist/bin/test.sh
  dist/bin/test_loader.js
  dist/bin/test_require_patch.js
INFO: Elapsed time: 12.049s, Critical Path: 7.22s
INFO: 16 processes: 1 remote cache hit, 13 internal, 2 linux-sandbox.
INFO: Build completed, 1 test FAILED, 16 total actions
//:test                                                                  FAILED in 3.7s
  /home/flolu/.cache/bazel/_bazel_flolu/ddcd1a310aa566a66906af93db7e118b/execroot/angular_bazel_architect/bazel-out/k8-fastbuild/testlogs/test/test.log

INFO: Build completed, 1 test FAILED, 16 total actions
error Command failed with exit code 3.
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04.1 LTS
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.6.1
Build label: 3.6.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Oct 6 13:11:20 2020 (1601989880)
Build timestamp: 1601989880
Build timestamp as int: 1601989880
  </code>
</pre>

**Rules_nodejs version:**

<pre>
  <code>
2.2.0
  </code>
</pre>

**Comment by alexeagle** [comment]
hmm, it works for me on mac
```
alex.eagle@Alexs-MacBook-Pro angular_bazel_architect % yarn test
yarn run v1.22.4
$ bazel test :test
INFO: Invocation ID: 87ce8b32-7bea-4dbd-a889-23dba18284eb
INFO: Analyzed target //:test (1 packages loaded, 9 targets configured).
INFO: Found 1 test target...
Target //:test up-to-date:
  dist/bin/test.sh
  dist/bin/test_loader.js
  dist/bin/test_require_patch.js
INFO: Elapsed time: 2.927s, Critical Path: 0.36s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
//:test                                                         (cached) PASSED in 10.5s
```

can you do some more digging? whose message is "No binary for ChromeHeadless" - I don't see that in the rules_nodejs codebase

**Comment by flolu** [comment]
I've now updated my comment with the full log.

It seems as if the error originates in **@angular-devkit/architect/cl**i: 
```
node_modules/@angular-devkit/architect-cli/bin/architect.js:76:55
```
