### ISSUE TITLE
'ts_library' 'module_name' attribute does not work with the angular compiler

### ISSUE THREAD

**Issue by KrauseStefan** [bazelbuild/rules_nodejs#2296]
# 🚀 feature request

### Relevant Rules
`ts_library` (`ng_ts_library`)

### Description
I am a little in doubt if this should have been a bug instead. I believe this is still considered work in progress so I opened it as a feature request.

The `ts_library` rule has a `module_name` attribute, it works fine for reqular `ts_library` but fails when running with
``` python 
compiler = "//tools:tsc_wrapped_with_angular",
use_angular_plugin = True,
```
The error message is 

``` sh
~/git/rules_nodejs/examples/angular $ bazel build //src
INFO: Invocation ID: 7c37fbf4-d7e3-4596-bb92-d9b96d51839f
INFO: Analyzed target //src:src (1 packages loaded, 9 targets configured).
INFO: Found 1 target...
ERROR: /home/skk/git/rules_nodejs/examples/angular/src/app/todos/BUILD.bazel:5:14: Compiling TypeScript (devmode) //src/app/todos:todos failed (Exit 1): tsc_wrapped_with_angular.sh failed: error executing command bazel-out/host/bin/tools/tsc_wrapped_with_angular.sh @@bazel-out/k8-fastbuild/bin/src/app/todos/todos_es5_tsconfig.json
Compilation failed Error: Symbol TodosComponent declared in /home/skk/.cache/bazel/_bazel_skk/e46a85f55839cdf197435c140a8b5281/execroot/examples_angular/bazel-out/k8-fastbuild/bin/src/lib/todos/todos.component.d.ts is not exported from @lib/todos/todos.module (import into /home/skk/.cache/bazel/_bazel_skk/e46a85f55839cdf197435c140a8b5281/execroot/examples_angular/src/app/todos/todos-app.component.ts)
    at AbsoluteModuleStrategy.emit (/home/skk/.cache/bazel/_bazel_skk/e46a85f55839cdf197435c140a8b5281/execroot/examples_angular/bazel-out/host/bin/tools/tsc_wrapped_with_angular.sh.runfiles/npm/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:157:23)
    at ReferenceEmitter.emit (/home/skk/.cache/bazel/_bazel_skk/e46a85f55839cdf197435c140a8b5281/execroot/examples_angular/bazel-out/host/bin/tools/tsc_wrapped_with_angular.sh.runfiles/npm/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:72:44)
    at ComponentDecoratorHandler.resolve (/home/skk/.cache/bazel/_bazel_skk/e46a85f55839cdf197435c140a8b5281/execroot/examples_angular/bazel-out/host/bin/tools/tsc_wrapped_with_angular.sh.runfiles/npm/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/component.js:426:62)
    at TraitCompiler.resolve (/home/skk/.cache/bazel/_bazel_skk/e46a85f55839cdf197435c140a8b5281/execroot/examples_angular/bazel-out/host/bin/tools/tsc_wrapped_with_angular.sh.runfiles/npm/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:399:50)
    at NgCompiler.resolveCompilation (/home/skk/.cache/bazel/_bazel_skk/e46a85f55839cdf197435c140a8b5281/execroot/examples_angular/bazel-out/host/bin/tools/tsc_wrapped_with_angular.sh.runfiles/npm/node_modules/@angular/compiler-cli/src/ngtsc/core/src/compiler.js:360:27)
    at NgCompiler.analyzeSync (/home/skk/.cache/bazel/_bazel_skk/e46a85f55839cdf197435c140a8b5281/execroot/examples_angular/bazel-out/host/bin/tools/tsc_wrapped_with_angular.sh.runfiles/npm/node_modules/@angular/compiler-cli/src/ngtsc/core/src/compiler.js:357:18)
    at NgCompiler.ensureAnalyzed (/home/skk/.cache/bazel/_bazel_skk/e46a85f55839cdf197435c140a8b5281/execroot/examples_angular/bazel-out/host/bin/tools/tsc_wrapped_with_angular.sh.runfiles/npm/node_modules/@angular/compiler-cli/src/ngtsc/core/src/compiler.js:329:22)
    at NgCompiler.prepareEmit (/home/skk/.cache/bazel/_bazel_skk/e46a85f55839cdf197435c140a8b5281/execroot/examples_angular/bazel-out/host/bin/tools/tsc_wrapped_with_angular.sh.runfiles/npm/node_modules/@angular/compiler-cli/src/ngtsc/core/src/compiler.js:288:36)
    at NgTscPlugin.createTransformers (/home/skk/.cache/bazel/_bazel_skk/e46a85f55839cdf197435c140a8b5281/execroot/examples_angular/bazel-out/host/bin/tools/tsc_wrapped_with_angular.sh.runfiles/npm/node_modules/@angular/compiler-cli/src/ngtsc/tsc_plugin.js:80:34)
    at createProgramAndEmit (/home/skk/.cache/bazel/_bazel_skk/e46a85f55839cdf197435c140a8b5281/execroot/examples_angular/bazel-out/host/bin/tools/tsc_wrapped_with_angular.sh.runfiles/npm/node_modules/@bazel/typescript/internal/tsc_wrapped/tsc_wrapped.js:328:38)
Target //src:src failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/skk/git/rules_nodejs/examples/angular/src/BUILD.bazel:51:14 Compiling TypeScript (devmode) //src/app/todos:todos failed (Exit 1): tsc_wrapped_with_angular.sh failed: error executing command bazel-out/host/bin/tools/tsc_wrapped_with_angular.sh @@bazel-out/k8-fastbuild/bin/src/app/todos/todos_es5_tsconfig.json
INFO: Elapsed time: 12.714s, Critical Path: 11.91s
INFO: 12 processes: 6 internal, 6 worker.
FAILED: Build did NOT complete successfully
```

### Describe the solution you'd like
I would like a solution where I am able to define a module with a name like
``` python
module_name = "@lib/todos",
```
and be able to reference it like this
``` ts
import {TodosModule} from '@lib/todos/todos.module';
```

I have created a example of how that could look with the angular example form this repository
https://github.com/KrauseStefan/rules_nodejs/pull/1

### Describe alternatives you've considered

Currently I am using `ng_module` form `@angular/bazel` but from what I can read it should be considered deprecated and `ng_ts_library` should be the future if you only need `Ivy` support.

**Comment by DavidANeil** [comment]
This sounds like a UnifiedModulesHost issue.
The old `ngc-wrapped` provided a `fileNameToModuleName` function to the compiler host that enabled some code paths within Angular that makes this module name mapping possible.

I have a patch for `tsc_wrapped` that makes this possible with ts_library.
But, the part that makes me doubt this is that a patch was also required to enable this strategy while using `ng_module` with Ivy as it used to be set off for all non-blaze invocations (i.e. off for everyone that isn't Google-internal).

**Comment by alexeagle** [comment]
Note that both `ts_library` and the `use_angular_plugin` feature use Bazel-specific custom code, which increases the surface area for issues like this and exposes you to risk of them not being well-maintained. We are going to recommend using `ts_project(compiler="@npm//@angular/compiler-cli")` for new code in the future, since this doesn't involve any custom code in rules_nodejs beyond the thin starlark layer in the `ts_project` implementation. Depending on where you are in your bazel migration, that path might make more sense for you.

**Comment by KrauseStefan** [comment]
Okay, 

There are a few things that `ts_library` does that I can't see addressed by `ts_project`.
The most important part is how do you handle that `ts_devserver`/`concatjs_devserver` needs named AMD modules, if the compiler is not adding it for every file? Some post processing step?
As I understand it the big speed improvement for large projects comes from avoiding bundling using the concat strategy that only works for named modules.

From what I can read the worker strategy has been created for `ts_project` but is in examples marked as experimental and does not work for windows, although the proposed solution does not seem to hard to implement. I might take a stab at it if I find some time and a good solution for the above concat/amd issue has been drafted.

**Comment by alexeagle** [comment]
Sorry I never answered here. You can still produce the same named AMD outputs, you just need to do it the way TypeScript documents. 

For example, in `@bazel/concatjs` we declare an amd-module name
https://github.com/bazelbuild/rules_nodejs/blob/1689fa185f9006dba198c079d848be18dceec38c/packages/concatjs/index.ts#L1
and use module=umd
https://github.com/bazelbuild/rules_nodejs/blob/1689fa185f9006dba198c079d848be18dceec38c/packages/concatjs/BUILD.bazel#L28
so that our output JS still works with concatjs users.

**Comment by alexeagle** [comment]
Leaving this issue open since this should be documented on https://bazelbuild.github.io/rules_nodejs/TypeScript.html

**Comment by normmcgarry** [comment]
Is there an example angular project that uses `ts_project` instead of `ts_library` somewhere if that is the recommended way to go? I'm just stumbling across this bug thread out of luck and would like to try that. Specifically, what do you do with html + css files when using `ts_project` instead?

**Comment by alexeagle** [comment]
@normmcgarry what do you expect the typescript compiler to do with the html and css files?

I do think we should remove `ts_library` from our examples in rules_nodejs though in preparation for deprecating it.

**Comment by normmcgarry** [comment]
I'm not sure. Was that a dumb question? What does `ts_library` do with them when you're compiling angular modules that have css and html files and using the `use_angular_plugin = True` flag? I would think `ts_project` would need to support those `ts_library` use cases. Maybe it doesn't. That's why I thought maybe an example exists if `ts_project` can do everything `ts_library` can.
