### ISSUE TITLE
Bazel version check fails

### ISSUE THREAD

**Issue by Arm1stice** [bazelbuild/rules_nodejs#2419]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 
`check_bazel_version`

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Not sure, `bazelisk` upgraded to 4.0.0 when I went to install the nodejs rules

### Description

 A clear and concise description of the problem...

When attempting to use the latest nodejs bazel rules with bazelisk running Bazel 4.0.0, an error is returned stating that the Bazel version is too old.

## 🔬 Minimal Reproduction

Will include below

## 🔥 Exception or Error

<pre><code>
Starting local Bazel server and connecting to it...
ERROR: Traceback (most recent call last):
        File "/home/arm1stice/Documents/iseamuseup/iracing-results/BUILD", line 4, column 13, in <toplevel>
                yarn_install(
        File "/home/arm1stice/.cache/bazel/_bazel_arm1stice/31fc3c259132486e35a0b3f28365aba7/external/build_bazel_rules_nodejs/index.bzl", line 73, column 23, in yarn_install
                _node_repositories()
        File "/home/arm1stice/.cache/bazel/_bazel_arm1stice/31fc3c259132486e35a0b3f28365aba7/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl", line 748, column 24, in node_repositories
                check_bazel_version(
        File "/home/arm1stice/.cache/bazel/_bazel_arm1stice/31fc3c259132486e35a0b3f28365aba7/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl", line 44, column 13, in check_bazel_version
                fail("\nCurrent Bazel version is lower than 0.2.1, expected at least %s\n" %
Error in fail: 
Current Bazel version is lower than 0.2.1, expected at least 2.1.0

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 4.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:33:24 2021 (1611214404)
Build timestamp: 1611214404
Build timestamp as int: 1611214404
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
3.0.0
  </code>
</pre>

**Anything else relevant?**

**Comment by Arm1stice** [comment]
Reproduction: https://github.com/Arm1stice/bazel-nodejs-bug-repro

**Comment by Arm1stice** [comment]
Seems I was too quick to open this issue. As you can see in the reproduction, I was using yarn_install inside of a BUILD file rather than the WORKSPACE file as intended. Because native.bazel_version is only available for rules run from WORKSPACE, the error was triggered.
