### ISSUE TITLE
`chdir` doesn't work under workers

### ISSUE THREAD

**Issue by Aghassi** [bazelbuild/rules_nodejs#2429]
When testing running `webpack` version `5` under rules_nodejs, using the `chdir` attribute on it errors with

```
events.js:291
      throw er; // Unhandled 'error' event
      ^
TypeError [ERR_WORKER_UNSUPPORTED_OPERATION]: process.chdir() is not supported in workers
    at process.unavailableInWorker [as chdir] (internal/process/worker_thread_only.js:12:11)
    at Object.<anonymous> (/private/var/tmp/_bazel_david.aghassi/a7bb26caa05a7d74fdb20e24a0f896f3/execroot/rh/bazel-out/darwin-fastbuild/bin/bazel/example/web/webpack5/__chdir.js__:1:9)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1155:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:446:5)
    at MessagePort.<anonymous> (internal/main/worker_thread.js:122:5)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (internal/worker.js:241:10)
    at Worker.[kOnMessage] (internal/worker.js:251:37)
    at MessagePort.<anonymous> (internal/worker.js:167:57)
    at MessagePort.emit (events.js:314:20)
    at MessagePort.onmessage (internal/worker/io.js:80:8)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:11:10) {
  code: 'ERR_WORKER_UNSUPPORTED_OPERATION'
```

Based on some splunking, it may have to do with either something on our end or on webpack's end... still looking. This is the only lead I have

https://github.com/moxystudio/node-cross-spawn/pull/127/files

https://github.com/bazelbuild/rules_nodejs/blob/1639ecfca0d712cec905e7fbb5dcad199204951b/internal/node/node.bzl#L250

**Comment by Aghassi** [comment]
The way I navigated around this was to use the `--run-under` flag https://github.com/bazelbuild/rules_nodejs/pull/2431/files#diff-6598581be26206e094d16c981932573b3540706b58bddda4a7961e98108993e0R9
