### ISSUE TITLE
Chaining tsconfigs by referencing a ts_config label doesn't seem to work

### ISSUE THREAD

**Issue by bduffany** [bazelbuild/rules_nodejs#2513]
On the latest rules_nodejs / Bazel / ubuntu 20.04, I'm unable to get the "chained" tsconfigs working as described [here](https://bazelbuild.github.io/rules_nodejs/TypeScript.html#ts_project-extends) -- minimal repro expressed as a failing test is [here](https://github.com/bazelbuild/rules_nodejs/pull/2512).

I'm getting this error:

```
/home/b/.cache/bazel/_bazel_b/9a83e2580c9584447d630e5ee533a2e1/sandbox/linux-sandbox/3/execroot/build_bazel_rules_nodejs/bazel-out/host/bin/packages/typescript/internal/ts_project_options_validator.js Error: packages/typescript/test/ts_project/extends_chain/server/tsconfig.json:error TS5058: The specified path does not exist: 'packages/typescript/test/ts_project/extends_chain/tsconfig.base.json'.

    at main (/home/b/.cache/bazel/_bazel_b/9a83e2580c9584447d630e5ee533a2e1/sandbox/linux-sandbox/3/execroot/build_bazel_rules_nodejs/bazel-out/host/bin/packages/typescript/internal/ts_project_options_validator.js:29:15)
    at Object.<anonymous> (/home/b/.cache/bazel/_bazel_b/9a83e2580c9584447d630e5ee533a2e1/sandbox/linux-sandbox/3/execroot/build_bazel_rules_nodejs/bazel-out/host/bin/packages/typescript/internal/ts_project_options_validator.js:89:28)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
ERROR: /home/b/code/rules_nodejs/packages/typescript/test/ts_project/extends_chain/server/BUILD.bazel:3:11: output 'packages/typescript/test/ts_project/extends_chain/server/_validate_main_options.optionsvalid.d.ts' was not created
ERROR: /home/b/code/rules_nodejs/packages/typescript/test/ts_project/extends_chain/server/BUILD.bazel:3:11: not all outputs were created or valid
Target //packages/typescript/test/ts_project/extends_chain/server:main failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.109s, Critical Path: 0.01s
INFO: 2 processes: 1 remote cache hit, 1 internal.
FAILED: Build did NOT complete successfully

```

**Comment by alexeagle** [comment]
fixed by #2512
