### ISSUE TITLE
module_root missing from ts_library LinkablePackageInfo for commonjs/none cases

### ISSUE THREAD

**Issue by vpanta** [bazelbuild/rules_nodejs#2580]
# 🐞 bug report

### Affected Rule
The issue is caused by the rule:  `ts_library`

### Is this a regression?
Not positive, but I think it should've worked before the addition of `LinkablePackageInfo`, which removed the usage of `module_root` for the package path.

### Description
NOTE: my use case is explicitly via a new rule executing a pre-defined `nodejs_binary` target, specifically `webpack-cli`. Today this is in a separate repo, but I'd hope to upstream it in the near future.

In my rule, I am externally loading `@build_bazel_rules_nodejs//internal/linker:link_node_modules.bzl`'s `module_mappings_aspect` for the additional provided files (namely, the webpack config). The webpack config imports from other local packages defined by `ts_library` rules, which are in the `deps` of my new rule.

We require `commonjs` module output from TS, and that doesn't seem to work appropriately with `LinkablePackageInfo`. I have no issue with `umd`, but `commonjs` or `none` need a `LinkablePackageInfo` which accounts for `module_root` as well.

## 🔬 Minimal Reproduction
https://github.com/vpanta/ts_lib_module_root_bug

## 🔥 Exception or Error
<pre><code>
master:~/src/ts_lib_module_root_bug$ bazel build :bundle --define=VERBOSE_LOGS=1 --sandbox_debug
Starting local Bazel server and connecting to it...

... node_modules mapping DEBUG statements omitted ...

DEBUG: /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] target //packages/package_bar:package_bar adding module mapping bar: ["__tslibrary__", "bazel-out/darwin-fastbuild/bin/packages/package_bar"]
DEBUG: /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] target //packages/package_foo:package_foo adding module mapping foo: ["__tslibrary__", "bazel-out/darwin-fastbuild/bin/packages/package_foo"]
DEBUG: /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] target //packages/package_bar:package_bar propagating module mapping bar: ["__tslibrary__", "bazel-out/darwin-fastbuild/bin/packages/package_bar"]
DEBUG: /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for //:bundle_contents
DEBUG: /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] target //packages/package_foo:package_foo propagating module mapping foo: ["__tslibrary__", "bazel-out/darwin-fastbuild/bin/packages/package_foo"]
DEBUG: /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for //:config
DEBUG: /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] Linking bar: ["__tslibrary__", "bazel-out/darwin-fastbuild/bin/packages/package_bar"]
DEBUG: /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] Linking foo: ["__tslibrary__", "bazel-out/darwin-fastbuild/bin/packages/package_foo"]
INFO: Analyzed target //:bundle (143 packages loaded, 3813 targets configured).
INFO: Found 1 target...
ERROR: /Users/vasilios/src/ts_lib_module_root_bug/BUILD.bazel:31:15: Bundling JavaScript bazel-out/darwin-fastbuild/bin/bundle.js [webpack] failed: (Exit 2): sandbox-exec failed: error executing command 
  (cd /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug && \
  exec env - \
    PATH=/Users/vasilios/bin:/Users/vasilios/src/mn/projects/fullstory/bin:/Users/vasilios/src/fsdev/tools/postgresql/bin:/Users/vasilios/src/fsdev/telemetry/bin:/Users/vasilios/src/fsdev/tools/circleci-cli:/Users/vasilios/src/fsdev/tools/mkcert:/Users/vasilios/src/fsdev/tools/buildozer:/Users/vasilios/src/fsdev/tools/buildifier:/Users/vasilios/src/fsdev/tools/ibazel:/Users/vasilios/src/fsdev/tools/bazel:/Users/vasilios/src/fsdev/tools/terraform:/Users/vasilios/src/fsdev/tools/sops:/Users/vasilios/src/fsdev/tools/packer:/Users/vasilios/src/fsdev/tools/helm:/Users/vasilios/src/fsdev/tools/google-cloud-sdk/bin:/Users/vasilios/src/fsdev/tools/flatbuffers/bin:/Users/vasilios/src/fsdev/tools/python/bin:/Users/vasilios/src/fsdev/tools/python3/bin:/Users/vasilios/src/fsdev/tools/node/bin:/Users/vasilios/src/fsdev/tools/jdk/bin:/Users/vasilios/src/fsdev/tools/go/bin:/Users/vasilios/src/fsdev/tools/cargo/bin:/Users/vasilios/src/fsdev/tools/google-cloud-sdk/bin:/Users/vasilios/Library/Android/sdk/platform-tools:/Users/vasilios/.cargo/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin \
    TMPDIR=/var/folders/sz/npxd4s153ksbl_6_v3c10x9h0000gp/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/sandbox.sb /var/tmp/_bazel_vasilios/install/97cf8d40e3de7fca7ef885fa763bde13/process-wrapper '--timeout=0' '--kill_delay=15' bazel-out/host/bin/external/npm/webpack-cli/bin/webpack-cli.sh bazel-out/darwin-fastbuild/bin/index.js --config bazel-out/darwin-fastbuild/bin/webpack.config.js --name //:bundle --env 'name=//:bundle' --output-path bazel-out/darwin-fastbuild/bin --output-filename bundle.js --resolve-alias-alias bazel-out/darwin-fastbuild/bin/packages/package_foo --resolve-alias-name foo --resolve-alias-alias bazel-out/darwin-fastbuild/bin/packages/package_bar --resolve-alias-name bar --resolve-modules . --resolve-modules node_modules '--bazel_node_modules_manifest=bazel-out/darwin-fastbuild/bin/_bundle.module_mappings.json') sandbox-exec failed: error executing command 
  (cd /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug && \
  exec env - \
    PATH=/Users/vasilios/bin:/Users/vasilios/src/mn/projects/fullstory/bin:/Users/vasilios/src/fsdev/tools/postgresql/bin:/Users/vasilios/src/fsdev/telemetry/bin:/Users/vasilios/src/fsdev/tools/circleci-cli:/Users/vasilios/src/fsdev/tools/mkcert:/Users/vasilios/src/fsdev/tools/buildozer:/Users/vasilios/src/fsdev/tools/buildifier:/Users/vasilios/src/fsdev/tools/ibazel:/Users/vasilios/src/fsdev/tools/bazel:/Users/vasilios/src/fsdev/tools/terraform:/Users/vasilios/src/fsdev/tools/sops:/Users/vasilios/src/fsdev/tools/packer:/Users/vasilios/src/fsdev/tools/helm:/Users/vasilios/src/fsdev/tools/google-cloud-sdk/bin:/Users/vasilios/src/fsdev/tools/flatbuffers/bin:/Users/vasilios/src/fsdev/tools/python/bin:/Users/vasilios/src/fsdev/tools/python3/bin:/Users/vasilios/src/fsdev/tools/node/bin:/Users/vasilios/src/fsdev/tools/jdk/bin:/Users/vasilios/src/fsdev/tools/go/bin:/Users/vasilios/src/fsdev/tools/cargo/bin:/Users/vasilios/src/fsdev/tools/google-cloud-sdk/bin:/Users/vasilios/Library/Android/sdk/platform-tools:/Users/vasilios/.cargo/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin \
    TMPDIR=/var/folders/sz/npxd4s153ksbl_6_v3c10x9h0000gp/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/sandbox.sb /var/tmp/_bazel_vasilios/install/97cf8d40e3de7fca7ef885fa763bde13/process-wrapper '--timeout=0' '--kill_delay=15' bazel-out/host/bin/external/npm/webpack-cli/bin/webpack-cli.sh bazel-out/darwin-fastbuild/bin/index.js --config bazel-out/darwin-fastbuild/bin/webpack.config.js --name //:bundle --env 'name=//:bundle' --output-path bazel-out/darwin-fastbuild/bin --output-filename bundle.js --resolve-alias-alias bazel-out/darwin-fastbuild/bin/packages/package_foo --resolve-alias-name foo --resolve-alias-alias bazel-out/darwin-fastbuild/bin/packages/package_bar --resolve-alias-name bar --resolve-modules . --resolve-modules node_modules '--bazel_node_modules_manifest=bazel-out/darwin-fastbuild/bin/_bundle.module_mappings.json')
[link_node_modules.js] manifest file: bazel-out/darwin-fastbuild/bin/_bundle.module_mappings.json
[link_node_modules.js] manifest contents: {
  "workspace": "ts_lib_module_root_bug",
  "bin": "bazel-out/darwin-fastbuild/bin",
  "roots": {
    "": "npm"
  },
  "modules": {
    "bar": "bazel-out/darwin-fastbuild/bin/packages/package_bar",
    "foo": "bazel-out/darwin-fastbuild/bin/packages/package_foo"
  }
}
[link_node_modules.js] startCwd: /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug
[link_node_modules.js] execroot: /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug
[link_node_modules.js] isExecroot: true
[link_node_modules.js] resolved npm workspace path to /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug/external/npm
[link_node_modules.js] creating symlink node_modules -> /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug/external/npm/node_modules
[link_node_modules.js] mapping hierarchy [{"name":"bar","link":"bazel-out/darwin-fastbuild/bin/packages/package_bar"},{"name":"foo","link":"bazel-out/darwin-fastbuild/bin/packages/package_foo"}]
[link_node_modules.js] creating symlink bar -> /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug/bazel-out/darwin-fastbuild/bin/packages/package_bar
[link_node_modules.js] creating symlink foo -> /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug/bazel-out/darwin-fastbuild/bin/packages/package_foo
BAZEL_NODE_MODULES_ROOTS=:npm
BAZEL_PATCH_ROOTS=/private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug,/private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug/node_modules,/private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug/external/npm/node_modules
bazel node patches enabled. roots: /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug,/private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug/node_modules,/private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug/external/npm/node_modules symlinks in these directories will not escape
[webpack-cli] Failed to load '/private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug/bazel-out/darwin-fastbuild/bin/webpack.config.js' config
[webpack-cli] Error: Cannot find module 'foo/foo'
Require stack:
- /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug/bazel-out/darwin-fastbuild/bin/webpack.config.js
- /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug/node_modules/webpack-cli/lib/webpack-cli.js
- /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug/node_modules/webpack-cli/lib/bootstrap.js
- /private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug/node_modules/webpack-cli/bin/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (/private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug/bazel-out/darwin-fastbuild/bin/webpack.config.js:3:15)
    at Module._compile (/private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug/bazel-out/darwin-fastbuild/bin/webpack.config.js',
    '/private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug/node_modules/webpack-cli/lib/webpack-cli.js',
    '/private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug/node_modules/webpack-cli/lib/bootstrap.js',
    '/private/var/tmp/_bazel_vasilios/8fa7ca6d0e54d0b018aaa17e16c170e5/sandbox/darwin-sandbox/10/execroot/ts_lib_module_root_bug/node_modules/webpack-cli/bin/cli.js'
  ]
}
Target //:bundle failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9.016s, Critical Path: 4.14s
INFO: 6 processes: 2 internal, 4 worker.
FAILED: Build did NOT complete successfully
</code></pre>

## 🌍  Your Environment
**Operating System:**
<pre>
  <code>
macOS Catalina 10.15.7
  </code>
</pre>

**Output of `bazel version`:**
<pre>
  <code>
Bazelisk version: v1.4.0
Build label: 4.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:38:50 2021 (1611214730)
Build timestamp: 1611214730
Build timestamp as int: 1611214730
  </code>
</pre>

**Rules_nodejs version:**
<pre>
  <code>
3.2.1
  </code>
</pre>

**Anything else relevant?**
Playing around, a quick change on [`ts_library`'s `LinkablePackageInfo` creation](https://github.com/bazelbuild/rules_nodejs/blob/d10e17cc4dc0e5f3753595c74134e2cc8dc4a8b9/packages/typescript/internal/build_defs.bzl#L351) to add `ctx.attr.module_root` to the path when `ctx.attr.devmode_module` is `commonjs` or `none` fixes it in those cases, but I haven't made a PR because I'm sure it's not going to be that simple, right?

**Comment by vpanta** [comment]
So I'd only tested `umd`, `commonjs`, and `none` (which generally would have a `tsc` output which works for a Node binary), however going further it seems like only `umd` and `amd` cause a `tsc` output which takes into account the `module_root` automatically. The other outputs need the `module_root` accounted for in the Path mapping in `LinkablePackageInfo`.
