### ISSUE TITLE
jasmine_node_test passes despite errors in test runner

### ISSUE THREAD

**Issue by katre** [bazelbuild/rules_nodejs#2688]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `jasmine_node_test`

### Description

 A clear and concise description of the problem...

I am setting up a new project to use Typescript and jasmine testing with Bazel and rules_nodejs. I am directly setting this up with Bazel, and not using node or npm, because I am familiar with Bazel.

When I set up my tests using `jasmine_node_test`, I saw that the test passes. But when I looked at the test log, I see failures because my test code cannot be found. The test runner should not pass if there are underlying errors.

I may very well have errors in my project, and if you can identify them I am grateful, but the test should not pass if it cannot be run.

## 🔬 Minimal Reproduction

Check out https://github.com/katre/ts-demo/tree/jasmine-test-runner.

```
$ bazel test //frontend:model_test 
INFO: Invocation ID: 720a5dcb-7af7-4744-8724-99764108875b
INFO: Analyzed target //frontend:model_test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
Target //frontend:model_test up-to-date:
  bazel-bin/frontend/model_test.sh
  bazel-bin/frontend/model_test_loader.js
  bazel-bin/frontend/model_test_require_patch.js
INFO: Elapsed time: 0.814s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
Test cases: finished with 1 passing and 0 failing out of 1 test cases

Executed 0 out of 1 test: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command INFO: Build completed successfully, 1 total action
```

## 🔥 Exception or Error

But when I look at the test log:
```
$ cat bazel-testlogs/frontend/model_test/test.log 
...
- /home/jcater/.cache/bazel/_bazel_jcater/494d7a0f1105ee0299d093a558bf667b/sandbox/linux-sandbox/14/execroot/ts-demo/bazel-out/k8-fastbuild/bin/frontend/model_test.sh.runfiles/npm/node_modules/@bazel/jasmine/jasmine_runner.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at frontend/model.spec.ts:1:1
    at /home/jcater/.cache/bazel/_bazel_jcater/494d7a0f1105ee0299d093a558bf667b/sandbox/linux-sandbox/14/execroot/ts-demo/bazel-out/k8-fastbuild/bin/frontend/model_test.sh.runfiles/ts-demo/frontend/model.spec.js:3:17
    at Object.<anonymous> (/home/jcater/.cache/bazel/_bazel_jcater/494d7a0f1105ee0299d093a558bf667b/sandbox/linux-sandbox/14/execroot/ts-demo/bazel-out/k8-fastbuild/bin/frontend/model_test.sh.runfiles/ts-demo/frontend/model.spec.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Loader.requireShim [as require_] (node_modules/jasmine/lib/loader.js:35:3)
    at node_modules/jasmine/lib/loader.js:28:12
    at new Promise (<anonymous>)
    at Loader.load (node_modules/jasmine/lib/loader.js:27:12)
    at Jasmine.loadSpecs (node_modules/jasmine/lib/jasmine.js:91:23)
    at Jasmine.execute (node_modules/jasmine/lib/jasmine.js:267:14)
(node:55) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:55) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## 🌍  Your Environment

**Operating System:** Linux
**Output of `bazel version`:** 4.0.0
**Rules_nodejs version:** 3.4.2

**Comment by katre** [comment]
If you look at the main branch on https://github.com/katre/ts-demo, the tests are executed (and pass) using `karma_web_test_suite`. I'd prefer to test non-UI code using pure server-side methods, however, rather than using a headless browser (which I understand is how karma works).
