### ISSUE TITLE
jasmine_node_test cannot find required modules when running remotely

### ISSUE THREAD

**Issue by huangw5** [bazelbuild/rules_nodejs#271]
The Angular jasmine_node_test tests [`//tools/ts-api-guardian:tests`](https://github.com/angular/angular/blob/master/tools/ts-api-guardian/BUILD.bazel#L53) always failed on RBE with error messages like:

```
6) cli: e2e test should generate golden file with --out
  Message:
    AssertionError: module.js:538
        throw err;
        ^

    Error: Cannot find module 'chalk'
        at Function.Module._resolveFilename (module.js:536:15)
        at Function.Module._load (module.js:466:25)
        at Module.require (module.js:579:17)
        at require (internal/module.js:11:18)
        at /b/f/w/run/bazel-out/k8-fastbuild/bin/tools/ts-api-guardian/tests.sh.runfiles/angular/tools/ts-api-guardian/ts-api-guardian/lib/cli.js:32:17
        at Object.defineProperty.value (/b/f/w/run/bazel-out/k8-fastbuild/bin/tools/ts-api-guardian/tests.sh.runfiles/angular/tools/ts-api-guardian/ts-api-guardian/lib/cli.js:20:17)
        at Object.<anonymous> (/b/f/w/run/bazel-out/k8-fastbuild/bin/tools/ts-api-guardian/tests.sh.runfiles/angular/tools/ts-api-guardian/ts-api-guardian/lib/cli.js:26:3)
        at Module._compile (module.js:635:30)
        at Object.Module._extensions..js (module.js:646:10)
        at Module.load (module.js:554:32)
    : expected 1 to equal 0
  Stack:
    error properties: null({ showDiff: true, actual: 1, expected: 0, constructor: Function, toJSON: Function })
        at <Jasmine>
        at Function.Module._resolveFilename (module.js:536:15)
        at Function.Module._load (module.js:466:25)
        at Module.require (module.js:579:17)
        at require (internal/module.js:11:18)
        at /b/f/w/run/bazel-out/k8-fastbuild/bin/tools/ts-api-guardian/tests.sh.runfiles/angular/tools/ts-api-guardian/ts-api-guardian/lib/cli.js:32:17
        at Object.defineProperty.value (/b/f/w/run/bazel-out/k8-fastbuild/bin/tools/ts-api-guardian/tests.sh.runfiles/angular/tools/ts-api-guardian/ts-api-guardian/lib/cli.js:20:17)
        at Object.<anonymous> (/b/f/w/run/bazel-out/k8-fastbuild/bin/tools/ts-api-guardian/tests.sh.runfiles/angular/tools/ts-api-guardian/ts-api-guardian/lib/cli.js:26:3)
        at Module._compile (module.js:635:30)
        at Object.Module._extensions..js (module.js:646:10)
        at Module.load (module.js:554:32)
        at <Jasmine>
        at UserContext.<anonymous> (/b/f/w/run/bazel-out/k8-fastbuild/bin/tools/ts-api-guardian/tests.sh.runfiles/angular/tools/ts-api-guardian/test/cli_e2e_test.js:64:25)
        at <Jasmine>
        at runCallback (timers.js:789:20)
        at tryOnImmediate (timers.js:751:5)
        at processImmediate [as _immediateCallback] (timers.js:722:5)
```
But they succeed when running locally.

I found the tests indeed cannot find the required modules. This is because the jasmine tests run in a different process than the test loader. Even though [`node_laoder.js`](https://github.com/bazelbuild/rules_nodejs/blob/master/internal/node/node_loader.js#L221) overrides the `_resolveFilename` function to find the required modules through [`module_mappings`](https://github.com/bazelbuild/rules_nodejs/blob/master/internal/node/node.bzl#L47), this doesn't help the jasmine tests running in a different process.

These tests succeed locally because they find the required modules from the `node_modules` in `execroot`, not the `node_loader.js`. I found the following directories when running the tests locally:

```
$ ls $HOME/.cache/bazel/_bazel_huangwe/775de14e511e52edfcaae56c2f956e4a/execroot/angular/
bazel-out
node_modules -> [some long path]
<ignored the remaining>
```
If I removed the symlink `node_modules`, the tests would failed just like running on RBE.

**Comment by alexeagle** [comment]
Looks like we should not spawn another process, or if we do, it should be invoked similarly to how `node_launcher.sh` does it.

/cc @gregmagolan

**Comment by huangw5** [comment]
It looks like the user's test spawns a new process. Can we prevent the users from doing that?

I tried setting the NODE_PATH env variable, but that didn't help because cli_e2e_test.ts overrides the env as well. 

I am wondering if we should make a symlink to node_modules from the test root.
