### ISSUE TITLE
`yarn precommit` fails on windows

### ISSUE THREAD

**Issue by filipesilva** [bazelbuild/rules_nodejs#284]
Running `yarn precommit` (or trying to commit in general) fails on windows with the following message:

```
kamik@RED-X1C6 MINGW64 /d/work/rules_nodejs (windows-absolute-runfiles)
$ yarn precommit
yarn run v1.5.1
$ check-clang-format "yarn format"
Error running git-clang-format: { Error: spawnSync D:\work\rules_nodejs\node_modules\clang-format\bin\git-clang-format ENOENT
    at _errnoException (util.js:1022:11)
    at spawnSync (child_process.js:579:20)
    at main (D:\work\rules_nodejs\node_modules\clang-format\bin\check-clang-format.js:63:18)
    at Object.<anonymous> (D:\work\rules_nodejs\node_modules\clang-format\bin\check-clang-format.js:82:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawnSync D:\\work\\rules_nodejs\\node_modules\\clang-format\\bin\\git-clang-format',
  path: 'D:\\work\\rules_nodejs\\node_modules\\clang-format\\bin\\git-clang-format',
  spawnargs: [ '--diff' ] }
error An unexpected error occurred: "Command failed.
Exit code: 2
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c check-clang-format \"yarn format\"
Directory: D:\\work\\rules_nodejs
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "D:\\work\\rules_nodejs\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by SnailCoil** [comment]
I'm having the same issue after having installed husky. I confirmed that `C:\Users\username\Documents\projects\project-name\node_modules\clang-format\bin\git-clang-format` exists

```
C:\Users\username\Documents\projects\project-name>git commit -m "add precommit hooks"
husky > pre-commit (node v10.4.1)
C:\Users\username\Documents\projects\project-name\node_modules\clang-format\bin\git-clang-format
Error running git-clang-format: { Error: spawnSync C:\Users\username\Documents\projects\project-name\node_modules\clang-format\bin\git-clang-format ENOENT
    at Object.spawnSync (internal/child_process.js:981:20)
    at spawnSync (child_process.js:588:24)
    at main (C:\Users\username\Documents\projects\project-name\node_modules\clang-format\bin\check-clang-format.js:64:18)
    at Object.<anonymous> (C:\Users\username\Documents\projects\project-name\node_modules\clang-format\bin\check-clang-format.js:83:22)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall:
   'spawnSync C:\\Users\\username\\Documents\\projects\\project-name\\node_modules\\clang-format\\bin\\git-clang-format',
  path:
   'C:\\Users\\username\\Documents\\projects\\project-name\\node_modules\\clang-format\\bin\\git-clang-format',
  spawnargs: [ '--diff' ] }
husky > pre-commit hook failed (add --no-verify to bypass)
```
