### ISSUE TITLE
Run nodejs_binary before another nodejs_binary

### ISSUE THREAD

**Issue by xnerhu** [bazelbuild/rules_nodejs#2969]
# 🚀 feature request

### Description

I'm looking for a feature where I can execute nodejs_binary before another nodejs_binary.

### Describe the solution you'd like

For example someone can have `nodejs_binary`, which populates database for testing and is very time consuming. It would be great to run it before some testing tool like jest automatically.

```starlark
nodejs_binary(
    name = "seed",
    data = [
        ":components_seed",
    ],
    entry_point = "db/seed.ts"
)

nodejs_binary(
    name = "app",
    data = [
        ":components",
    ],
    entry_point = "src/index.ts",
    run = [
       ":seed"     
    ]
)
```

**Comment by alexeagle** [comment]
This feature wouldn't live in rules_nodejs, you already have options for composing programs:
- wrap with a `sh_binary`
- change one node program to spawn the other as a subprocess
- use the `--require` flag to node to run some arbitrary script before evaluating the entry_point

does that help?

**Comment by xnerhu** [comment]
Is there a way to preserve arguments inside `sh` file generated by `nodejs_binary` ? I went with subprocess and I have to repeat  arguments.

```starlark
mikro_orm(
    name = "schema_update",
    args = [
        "schema:update",
        "--run",
        "--fk-checks",
    ],
)
```

```ts
execa(resolve(__dirname, "../schema_upate.sh"),
    ["schema:update", "--run", "--fk-checks"]
)
```

**Comment by xnerhu** [comment]
I have been experimenting with `nodejs_binary` and `sh_binary`.  But I there is an issue with resolving node patches.

```starlark
nodejs_binary(
    name = "seed",
    data = [
        ":components_db",
    ],
    entry_point = "db/seed.ts",
)

sh_binary(
    name = "run_seed",
    srcs = ["run_seed.sh"],
    args = ["$(location :seed)"],
    data = [
        ":seed",
        "@bazel_tools//tools/bash/runfiles",
    ],
)
```

```bash
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '/c/users/runner~1/_bazel~1/l3cg6sor/execroot/init/bazel-~1/x64_wi~1/bin/packages/app/run_se~2.run/init/C:\users\runneradmin\_bazel_runneradmin\l3cg6sor\execroot\init\bazel-out\x64_windows-fastbuild\bin\packages\app\run_seed.exe.runfiles/build_bazel_rules_nodejs/internal/node/node_patches.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1231:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:468:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:71:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
```

[Repro](https://github.com/xnerhu/sh_binary_repro/tree/master/packages/app)
