### ISSUE TITLE
Improve bash interpreter shebang

### ISSUE THREAD

**Issue by kczulko** [bazelbuild/rules_nodejs#3141]
# 🐞 bug report

### Affected Rule

`architect` from architect-cli

`load("@npm//@angular-devkit/architect-cli:index.bzl", "architect")`

### Is this a regression?

I don't think so.

### Description

Hello,
I'm trying to setup `architect(...)` build just like you did in the examples directory. Fortunately, I'm working on NixOs and now I see the following failure:

```
 Error: spawn /home/kczulko/.cache/bazel/_bazel_kczulko/8f7b6114e063cc57a6c58fc1f8b8f847/sandbox/linux-sandbox/13/execroot/eagle/bazel-out/host/bin/external/npm/@angular-devkit/architect-cli/bin/architect.sh.runfiles/build_bazel_rules_nodejs/internal/node/_node_bin/node ENOENT
     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
     at onErrorNT (internal/child_process.js:467:16)
     at processTicksAndRejections (internal/process/task_queues.js:82:21)
``` 

I think the reason for this errors comes from the aforementioned `node` script and its shebang:
```
$ cat node
#!/bin/bash
export NP_SUBPROCESS_NODE_DIR="/home/kczulko/.cache/bazel/_bazel_kczulko/8f7b6114e063cc57a6c58fc1f8b8f847/sandbox/linux-sandbox/13/execroot/eagle/bazel-out/host/bin/external/npm/@angular-devkit/architect-cli/bin/architect.sh.runfiles/build_bazel_rules_nodejs/internal/node/_node_bin"
export PATH="/home/kczulko/.cache/bazel/_bazel_kczulko/8f7b6114e063cc57a6c58fc1f8b8f847/sandbox/linux-sandbox/13/execroot/eagle/bazel-out/host/bin/external/npm/@angular-devkit/architect-cli/bin/architect.sh.runfiles/build_bazel_rules_nodejs/internal/node/_node_bin":$PATH
if [[ ! "${@}" =~ "node_patches.js" ]]; then
  exec /nix/store/0abyd3fvy7f0zqi6vjhzvdv7z5w4lb8j-nodejs-14.17.5/bin/node --preserve-symlinks --require "/home/kczulko/.cache/bazel/_bazel_kczulko/8f7b6114e063cc57a6c58fc1f8b8f847/sandbox/linux-sandbox/13/execroot/eagle/bazel-out/host/bin/external/npm/@angular-devkit/architect-cli/bin/architect.sh.runfiles/build_bazel_rules_nodejs/internal/node/node_patches.js" "$@"
else
  exec /nix/store/0abyd3fvy7f0zqi6vjhzvdv7z5w4lb8j-nodejs-14.17.5/bin/node --preserve-symlinks "$@"
fi
```

I think it's being generated here: https://github.com/bazelbuild/rules_nodejs/blob/aa09b5796faaf2470b84246a8f00e6e27181c63b/packages/node-patches/src/subprocess.ts#L32

Can I replace shebang to `#!/usr/bin/env bash` just like it is now within the `architect.sh` script (https://github.com/bazelbuild/rules_nodejs/blob/f72e95661d914d78f44d860f5f1d4281a58b7ab2/internal/node/launcher.sh#L1)? I'll patch it and update this thread how it went.

## 🔬 Minimal Reproduction

This is really complicated and including custom bazel wrapper together with ongoing nipkgs bazel fix so I won't give full repro env here.

## 🔥 Exception or Error

```
 Error: spawn /home/kczulko/.cache/bazel/_bazel_kczulko/8f7b6114e063cc57a6c58fc1f8b8f847/sandbox/linux-sandbox/13/execroot/eagle/bazel-out/host/bin/external/npm/@angular-devkit/architect-cli/bin/architect.sh.runfiles/build_bazel_rules_nodejs/internal/node/_node_bin/node ENOENT
     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
     at onErrorNT (internal/child_process.js:467:16)
     at processTicksAndRejections (internal/process/task_queues.js:82:21)
``` 

## 🌍  Your Environment

**Operating System: NixOs 21.11
**Output of `bazel version`: `bazel 4.1.0- (@non-git)`
**Rules_nodejs version: `https://github.com/bazelbuild/rules_nodejs/releases/download/4.4.6/rules_nodejs-4.4.6.tar.gz`

**Comment by alexeagle** [comment]
I can make that fix now. You're right, we should always use `env` to locate bash.

**Comment by alexeagle** [comment]
🥧 issue

**Comment by alexeagle** [comment]
hmm, we are missing something since that fix makes the build fail

```
% USE_BAZEL_VERSION=4.2.0 bazel test //packages/terser/...

ERROR: /Users/alexeagle/Projects/rules_nodejs/packages/terser/test/directory_input/BUILD.bazel:10:16: Minifying JavaScript packages/terser/test/directory_input/out.min [terser] failed: (Exit 2): terser.sh failed: error executing command bazel-out/host/bin/packages/terser/bin/terser.sh bazel-out/darwin_arm64-fastbuild/bin/packages/terser/test/directory_input/dir --output ... (remaining 6 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
[terser/index.js] errored: bazel-out/darwin_arm64-fastbuild/bin/packages/terser/test/directory_input/dir/input1.js
OUT:
ERR: env: bash: No such file or directory

code: 127
[terser/index.js] errored: bazel-out/darwin_arm64-fastbuild/bin/packages/terser/test/directory_input/dir/input2.js
OUT:
ERR: env: bash: No such file or directory

code: 127
[terser/index.js] terser errored processing javascript in directory.
```

I am guessing `/usr/bin/env` expects to see something in the environment, but some places where we run this node wrapper don't have that.
