### ISSUE TITLE
[5.1.0] Error Package "polymer-bridges" refers to a non-existing file

### ISSUE THREAD

**Issue by davido** [bazelbuild/rules_nodejs#3324]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: 

```python
yarn_install(
    name = "ui_npm",
    args = [
        "--prod",
        # By default, yarn install all optional dependencies.
        # In some cases, it installs a lot of additional dependencies which
        # are not required (for example, "resemblejs" has one optional
        # dependencies "canvas" that leads to tens of additional dependencies).
        # Each additional dependency requires a license even if it is not used
        # in our code.  We want to ensure that all optional dependencies are
        # explicitly added to package.json.
        "--ignore-optional",
    ],
    frozen_lockfile = False,
    package_json = "//:polygerrit-ui/app/package.json",
    yarn_lock = "//:polygerrit-ui/app/yarn.lock",
)
```

### Is this a regression?

Yes, the previous version in which this bug was not present was: 4.6.1.

### Description

It seems that `polymer-bridges` dependencies isn't resolved
correctly after the upgrade any more.

In the `polygerrit-ui/app/package.json`, it's defined as:

```
   "polymer-bridges": "file:../../polymer-bridges/",
```

and is in fact git module, defined as follow in `.gitmodules`:

```
[submodule "polymer-bridges"]
	path = polymer-bridges
	url = ../polymer-bridges
	branch = .
```

## 🔬 Minimal Reproduction

Fetch [Gerrit Code Review](https://gerrit.googlesource.com) recursively, 
fetch this CL: [1] and run this command: `bazel fetch @ui_npm//:node_modules`.

[1] https://gerrit-review.googlesource.com/c/gerrit/+/330241

## 🔥 Exception or Error

```bash
  $ bazel fetch @ui_npm//:node_modules
Starting local Bazel server and connecting to it...
DEBUG: /home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/build_bazel_rules_nodejs/index.bzl:65:14: node_repository attribute not set and no repository named 'nodejs_toolchains' exists; installing default node
DEBUG: /home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/build_bazel_rules_nodejs/index.bzl:73:14: yarn_install#yarn attribute not set and no repository named 'yarn' exists; installing default yarn
INFO: Repository ui_npm instantiated at:
  /home/davido/projects/gerrit/WORKSPACE:161:13: in <toplevel>
  /home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/build_bazel_rules_nodejs/index.bzl:83:18: in yarn_install
Repository rule yarn_install defined at:
  /home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:974:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'ui_npm':
   Traceback (most recent call last):
	File "/home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 965, column 13, in _yarn_install_impl
		fail("yarn_install failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: yarn_install failed: yarn install v1.22.11
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 (error Package "polymer-bridges" refers to a non-existing file '"/home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/ui_npm/_/polymer-bridges"'.
)
ERROR: /home/davido/projects/gerrit/WORKSPACE:161:13: fetching yarn_install rule //external:ui_npm: Traceback (most recent call last):
	File "/home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 965, column 13, in _yarn_install_impl
		fail("yarn_install failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: yarn_install failed: yarn install v1.22.11
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 (error Package "polymer-bridges" refers to a non-existing file '"/home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/ui_npm/_/polymer-bridges"'.
)
ERROR: no such package '@ui_npm//': yarn_install failed: yarn install v1.22.11
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 (error Package "polymer-bridges" refers to a non-existing file '"/home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/ui_npm/_/polymer-bridges"'.
)
Loading: 0 packages loaded
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
$ bazelisk version
Bazelisk version: {STABLE_VERSION}
Build label: 5.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jan 19 14:08:54 2022 (1642601334)
Build timestamp: 1642601334
Build timestamp as int: 1642601334
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
5.1.0
  </code>
</pre>

**Anything else relevant?**

Probably related #3291?

**Comment by alexeagle** [comment]
Did you try the same resolution as from #3291? the default location we place the node_modules tree has changed, so you may need to point it back at the root so that the relative pathing still works.

**Comment by davido** [comment]
But we can't put it back to the root, because there we have different `node_modules`:

```python
yarn_install(
    name = "npm",
    frozen_lockfile = False,
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)
```

Generally we have 5 different `node_modules` locations:

- npm, root in /
- ui_dev_npm, root in polygerrit-ui
- ui_npm, root in polygerrit-ui/app
- tools_npm, root in tools/node_tools
- plugins_npm, root in plugins

The problem seems to only be related to `polymer-bridges` dependency, that we consume directly from the workspace. The problem persists, even if I move the `polymer-bridges` from root of the workspace to the `polygerrit-ui/app` and adapt the `polygerrit-ui/app/package.json` correspondingly:

```
  "polymer-bridges": "file:polymer-bridges/",
```

**Comment by davido** [comment]
To further track down the problem, I patched gerrit to consume `build_bazel_rules_nodejs` from local directory:

```diff
diff --git a/WORKSPACE b/WORKSPACE
index ce36bc2515..62d3dd99cb 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -56,10 +56,15 @@ load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
 
 protobuf_deps()
 
-http_archive(
+#http_archive(
+#    name = "build_bazel_rules_nodejs",
+#    sha256 = "c077680a307eb88f3e62b0b662c2e9c6315319385bc8c637a861ffdbed8ca247",
+#    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/5.1.0/rules_nodejs-5.1.0.tar.gz"],
+#)
+
+local_repository(
     name = "build_bazel_rules_nodejs",
-    sha256 = "c077680a307eb88f3e62b0b662c2e9c6315319385bc8c637a861ffdbed8ca247",
-    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/5.1.0/rules_nodejs-5.1.0.tar.gz"],
+    path = "/home/davido/projects/rules_nodejs-5.1.0",
 )
```

And changed this line in `rules_nodejs`:

```diff
diff --git a/internal/npm_install/npm_install.bzl b/internal/npm_install/npm_install.bzl
index 6e14ba0e..d28a1f1e 100644
--- a/internal/npm_install/npm_install.bzl
+++ b/internal/npm_install/npm_install.bzl
@@ -901,7 +901,7 @@ def _yarn_install_impl(repository_ctx):
         # ‘https://domain/artifactory/api/npm/npm/’“.)
         repository_ctx.file(
             "_yarn.sh",
-            content = """#!/usr/bin/env bash
+            content = """#!/usr/bin/bash -x
 # Immediately exit if any command fails.
 set -e
 unset YARN_IGNORE_PATH
```

I also had to add WORKSPACE file with this content to make Bazel happy:

rules_nodejs-5.1.0/WORKSPACE
```
workspace(name = "build_bazel_rules_nodejs")
```

Now I am getting verbose output from the failure:

```bash
   $ bazelisk fetch @ui_npm//:node_modules
DEBUG: /home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/build_bazel_rules_nodejs/index.bzl:65:14: node_repository attribute not set and no repository named 'nodejs_toolchains' exists; installing default node
DEBUG: /home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/build_bazel_rules_nodejs/index.bzl:73:14: yarn_install#yarn attribute not set and no repository named 'yarn' exists; installing default yarn
+ set -e
+ unset YARN_IGNORE_PATH
+ unset INIT_CWD
+ unset npm_config_registry
+ cd /home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/ui_npm/_/polygerrit-ui/app
+ /home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/yarn/bin/yarn --mutex network --prod --ignore-optional
yarn install v1.22.11
[1/4] Resolving packages...
error Package "polymer-bridges" refers to a non-existing file '"/home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/ui_npm/_/polygerrit-ui/app/polymer-bridges"'.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
INFO: Repository ui_npm instantiated at:
  /home/davido/projects/gerrit/WORKSPACE:166:13: in <toplevel>
  /home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/build_bazel_rules_nodejs/index.bzl:83:18: in yarn_install
Repository rule yarn_install defined at:
  /home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:974:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'ui_npm':
   Traceback (most recent call last):
	File "/home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 965, column 13, in _yarn_install_impl
		fail("yarn_install failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: yarn_install failed: yarn install v1.22.11
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 (+ set -e
+ unset YARN_IGNORE_PATH
+ unset INIT_CWD
+ unset npm_config_registry
+ cd /home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/ui_npm/_/polygerrit-ui/app
+ /home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/yarn/bin/yarn --mutex network --prod --ignore-optional
error Package "polymer-bridges" refers to a non-existing file '"/home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/ui_npm/_/polygerrit-ui/app/polymer-bridges"'.
)
ERROR: /home/davido/projects/gerrit/WORKSPACE:166:13: fetching yarn_install rule //external:ui_npm: Traceback (most recent call last):
	File "/home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 965, column 13, in _yarn_install_impl
		fail("yarn_install failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: yarn_install failed: yarn install v1.22.11
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 (+ set -e
+ unset YARN_IGNORE_PATH
+ unset INIT_CWD
+ unset npm_config_registry
+ cd /home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/ui_npm/_/polygerrit-ui/app
+ /home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/yarn/bin/yarn --mutex network --prod --ignore-optional
error Package "polymer-bridges" refers to a non-existing file '"/home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/ui_npm/_/polygerrit-ui/app/polymer-bridges"'.
)
ERROR: no such package '@ui_npm//': yarn_install failed: yarn install v1.22.11
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 (+ set -e
+ unset YARN_IGNORE_PATH
+ unset INIT_CWD
+ unset npm_config_registry
+ cd /home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/ui_npm/_/polygerrit-ui/app
+ /home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/yarn/bin/yarn --mutex network --prod --ignore-optional
error Package "polymer-bridges" refers to a non-existing file '"/home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/ui_npm/_/polygerrit-ui/app/polymer-bridges"'.
)
Loading: 0 packages loaded
```

**Comment by davido** [comment]
OK, I've found the workaround that consists of three steps:

1. Consume `polymer-bridges` from GitHub mirror instead of from git submodule
2. As you you suggested, set `package_path = "/"`
3. Overwrite `exports_directories_only = False`

The latest CL is here: [1].

[1] https://gerrit-review.googlesource.com/c/gerrit/+/330241

**Comment by davido** [comment]
But even with the workaround, the tests are failing after the upgrade:

```
 $> bazel test //polygerrit-ui:karma_test
[...]
DEBUG: /home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/build_bazel_rules_nodejs/index.bzl:65:14: node_repository attribute not set and no repository named 'nodejs_toolchains' exists; installing default node
DEBUG: /home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/build_bazel_rules_nodejs/index.bzl:73:14: yarn_install#yarn attribute not set and no repository named 'yarn' exists; installing default yarn
ERROR: /home/davido/projects/gerrit/polygerrit-ui/app/BUILD:67:11: in ts_project rule //polygerrit-ui/app:compile_pg_with_tests: 
Traceback (most recent call last):
	File "/home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/npm/@bazel/typescript/internal/ts_project.bzl", line 223, column 17, in _ts_project_impl
		run_node(
	File "/home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/build_bazel_rules_nodejs/internal/providers/node_runtime_deps_info.bzl", line 106, column 51, in run_node
		modules_manifest = write_node_modules_manifest(
	File "/home/davido/.cache/bazel/_bazel_davido/27a001f4182820ef315d8d2d4f1edafe/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl", line 124, column 25, in write_node_modules_manifest
		fail("All npm dependencies at the path '%s' must come from a single workspace. Found '%s' and '%s'." % (path, other_workspace, workspace))
Error in fail: All npm dependencies at the path '' must come from a single workspace. Found 'tools_npm' and 'ui_dev_npm'.
ERROR: /home/davido/projects/gerrit/polygerrit-ui/app/BUILD:67:11: Analysis of target '//polygerrit-ui/app:compile_pg_with_tests' failed
ERROR: Analysis of target '//polygerrit-ui:karma_test' failed; build aborted: 
INFO: Elapsed time: 79.051s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (746 packages loaded, 25459 targets configured)
FAILED: Build did NOT complete successfully (746 packages loaded, 25459 targets configured)
```

**Comment by alexeagle** [comment]
You could specify the node and yarn to use, rather than getting defaults.

**Comment by davido** [comment]
>

Thanks. This fixed it:

```diff
-load("@build_bazel_rules_nodejs//:index.bzl", "yarn_install")
+load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories", "yarn_install")
+
+node_repositories(
+    node_version = "16.13.2",
+    yarn_version = "1.22.17",
+)
```

**Comment by davido** [comment]
It's resolved now. Quoting the commit message in this CL: [1].

```
The new dependency on @bazel/concatjs is unfortunate, but that is where
ts_library has moved. And we have spent 2 hours trying to get ts_project
to work instead, and failed. So I guess we have to live with this for
now.

Without `symlink_node_modules` in `yarn_install` the `node_modules`
directory would not appear anymore next to the package.json file. It
would only appear in Bazel's out directories. That breaks all sorts of
things, `server.go` for example cannot cope at all without
`node_modules` being present.
```

[1] https://gerrit-review.googlesource.com/c/gerrit/+/330241
