### ISSUE TITLE
Fails to create node_modules/.bin/BUILD.bazel if node_modules/.bin does not exist

### ISSUE THREAD

**Issue by qzmfranklin** [bazelbuild/rules_nodejs#486]
# 🐞 bug report

### Affected Rule
`yarn_install`
`npm_install`

 The issue is caused by the rule: 

### Is this a regression?
No

 Yes, the previous version in which this bug was not present was: ....

### Description
 A clear and concise description of the problem...
`yarn_install` rule fails to create `node_modules/.bin/BUILD.bazel` if the `package.json` file does not contain any package that has an executable.

## 🔬 Minimal Reproduction

`package.json`
```json
{
    "dependencies": {
        "lodash": "^4.17.11"
    }
}
```
`yarn.lock` is generated by running `yarn` in the containing directory of the above `package.json`.

Add the following to `WORKSPACE`:
```python
load(
    '@build_bazel_rules_nodejs//:defs.bzl',
    'yarn_install',
)
yarn_install(
    name = 'exp_deps',
    package_json = r'''//:package.json''',
    yarn_lock = r'''//:yarn.lock''',
)

```

Then running the following command
```bash
bazel build @exp_deps//lodash
```
would yield the following errors:
```bash
ERROR: no such package '@exp_deps//lodash': Traceback (most recent call last):
        File "/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 243
                _create_build_file(repository_ctx, node)
        File "/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 88, in _create_build_file
                fail(("node failed: \nSTDOUT:\n%s\nST...)))
node failed:
STDOUT:

STDERR:
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir 'node_modules/.bin'
    at Object.readdirSync (fs.js:786:3)
    at listFiles (/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/external/exp_deps/generate_build_file.js:168:8)
    at generateRootBuildFile (/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/external/exp_deps/generate_build_file.js:96:20)
    at main (/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/external/exp_deps/generate_build_file.js:87:3)
    at Object.<anonymous> (/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/external/exp_deps/generate_build_file.js:57:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
INFO: Elapsed time: 2.570s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 18.04.1 amd64
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 0.19.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Nov 19 16:25:09 2018 (1542644709)
Build timestamp: 1542644709
Build timestamp as int: 1542644709

  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant?**

**Comment by qzmfranklin** [comment]
If I do a `yarn add -D pug`, then this error would go away.

The reason is that `rules_nodejs` does not check the existence of `node_modules/.bin` prior to generating the `BUILD` file inside it.
