### ISSUE TITLE
Simple express example is broken

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_nodejs#60]
See here: https://github.com/mattmoor/rules_nodejs-1/tree/express-example

The `http` example works:
```shell
$ bazel run :http
INFO: Analysed target //:http (0 packages loaded).
INFO: Found 1 target...
Target //:http up-to-date:
  bazel-bin/http_bin.sh
  bazel-bin/http
INFO: Elapsed time: 0.232s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action

INFO: Running command line: bazel-bin/http
Server running at http://127.0.0.1:8000/
```

However, the express version doesn't:
```shell
$ bazel run :express
INFO: Analysed target //:express (0 packages loaded).
INFO: Found 1 target...
Target //:express up-to-date:
  bazel-bin/express_bin.sh
  bazel-bin/express
INFO: Elapsed time: 0.240s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action

INFO: Running command line: bazel-bin/express
failed to load main  TypeError: Cannot set property 'o' of undefined
    at Object.<anonymous> (/home/mattmoor/rules_nodejs/examples/express/node_modules/debug/src/node.js:85:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mattmoor/rules_nodejs/examples/express/node_modules/debug/src/index.js:9:20)
    at Module._compile (module.js:635:30)
ERROR: Non-zero return code '1' from command: Process exited with status 1
```

I'm assuming this simple example works (I'm not a Node.js guy), I am following [this](http://expressjs.com/en/starter/hello-world.html).

**Comment by alexeagle** [comment]
I hit the same issue - a change to the module resolution order broke the `debug` npm module.
Was just reverted in https://github.com/bazelbuild/rules_nodejs/commit/a015ac1b8fbfb7fbe7e9d54835166f5d9ac81890

**Comment by mattmoor** [comment]
Cool thanks, that works for me :)
