### ISSUE TITLE
Monorepo pattern - jasmine failing when importing through new method

### ISSUE THREAD

**Issue by charandas** [bazelbuild/rules_nodejs#742]
# 🐞 bug report

### Affected Rule
`jasmine_node_test`

### Is this a regression?
Kinda when you drop support to do the following:
```
load("@build_bazel_rules_nodejs//:defs.bzl", "jasmine_node_test")
## asking users to instead do:
load("@npm_bazel_jasmine//:index.bzl", "jasmine_node_test")
```
### Description

Currently, if I use the new approach, I get the error that mixing npm workspaces is not allowed.

## 🔬 Minimal Reproduction

I am using a monorepo pattern, where my `WORKSPACE` does not immediately contain any `npm`/`nodejs` packages. The packages to be tested are in sub-directory, which is for me `src`. Each of the packages have their own runtime dependencies (their own `package.json/yarn.lock`).

For example, here are my mixed npm WORKSPACEs:

```
load("@npm_bazel_jasmine//:index.bzl", "jasmine_node_test")
# I have tried installing @bazel/jasmine in npm_challenge WORKSPACE, but
# @npm_challenge_bazel_jasmine won't magically work similar to @npm_bazel_jasmine

jasmine_node_test(
  name = "test",
  srcs = [
    "//src/challenge:handler.test.js"
  ],
  data = [
    "//src/challenge:handler.js",
    "//src/challenge:package.json",
    "@npm_challenge//pkg-1",
    "@npm_challenge//pkg-2",
  ],
  deps = [
    "@npm_challenge//jasmine" # note that, I omit this when using the new approach, and it works so long as I don't have any of @npm_challenge lines under data
  ]
)
```

## 🔥 Exception or Error

<pre><code>
ERROR: /Users/charandas/source/org/project/src/challenge/BUILD.bazel:4:1: in nodejs_test rule //src/challenge:test:
Traceback (most recent call last):
        File "/Users/charandas/source/org/project/src/challenge/BUILD.bazel", line 4
                nodejs_test(name = 'test')
        File "/private/var/tmp/_bazel_charandas/e62efef3a3fa01ec24a474c3d5ec7305/external/build_bazel_rules_nodejs/internal/node/node.bzl", line 135, in _nodejs_binary_impl
                _write_loader_script(ctx)
        File "/private/var/tmp/_bazel_charandas/e62efef3a3fa01ec24a474c3d5ec7305/external/build_bazel_rules_nodejs/internal/node/node.bzl", line 87, in _write_loader_script
                _compute_node_modules_root(ctx)
        File "/private/var/tmp/_bazel_charandas/e62efef3a3fa01ec24a474c3d5ec7305/external/build_bazel_rules_nodejs/internal/node/node.bzl", line 63, in _compute_node_modules_root
                fail(("All npm dependencies need to c...)))
All npm dependencies need to come from a single workspace. Found 'npm_challenge/node_modules' and 'npm/node_modules'.
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
    MacOS Mojave
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 0.25.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed May 1 21:47:49 2019 (1556747269)
Build timestamp: 1556747269
Build timestamp as int: 1556747269
  </code>
</pre>

Maybe I am missing something simple, I really don't know how the magical `npm_bazel_jasmine` workspace appears. I believe the answer to my quandary lies somewhere in there.

**Comment by charandas** [comment]
I think I am looking to be able to override this [line](https://github.com/bazelbuild/rules_nodejs/blob/master/packages/jasmine/src/jasmine_node_test.bzl#L31), where it defaults to using `@npm` workspace: 

```
jasmine = Label("@npm//@bazel/jasmine"),
```

I am able to specify while invoking `jasmine_node_test` like below, and then the issue is resolved for me. It would be good to document this.
```
jasmine_node_test(
...
  jasmine  = "@npm_challenge//@bazel/jasmine",
...
)
```

Also, I did a little more digging, and I now understand how `npm_bazel_jasmine` comes to be. It's the magic with `bazelWorkspaces` in `pacakge.json` and `install_bazel_dependencies`.

Using the `npm_bazel_jasmine` and new method of importing `jasmine_node_test` has nothing antagonistic with monorepo pattern, and having more than 1 `npm_install/yarn_install` workspace. It was the `jasmine` parameter that was leading to the mixing.
