### ISSUE TITLE
yarn install fails at random

### ISSUE THREAD

**Issue by gorilych** [bazelbuild/rules_nodejs#930]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: @nodejs//:yarn

### Is this a regression?

 I don't know.

### Description

`@nodejs//:yarn` fails in from time to time while building npm packages at `require` statement. Looks like some kind of a race condition to me, maybe node_loader.js is not loaded to override `_resolveFilename` - but I am not expert in it to judge.

## 🔬 Minimal Reproduction

I've prepared sample repo https://github.com/gorilych/rules_nodejs_bug1 - meaningful files are package.json and WORKSPACE. Build.bazel is empty.

To reproduce, try to run `@nodejs//:yarn` for this repo with bazel 0.28.0, f.e.:

`sudo docker run -ti --entrypoint /bin/bash l.gcr.io/google/bazel:0.28.0 -c "git clone https://github.com/gorilych/rules_nodejs_bug1.git; cd rules_nodejs_bug1; bazel run @nodejs//:yarn"`

IMPORTANT: it fails randomly, so you might need to run it like 5 times to see the error. In our CI environment on a real project it may fail like 3 times in a row.

## 🔥 Exception or Error

<pre><code>
Error: Cannot find module '../'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/rules_nodejs_bug1/node_modules/bcrypt/node_modules/.bin/node-pre-gyp:15:20)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
</code></pre>

## 🌍  Your Environment

I run bazel inside linux docker container l.gcr.io/google/bazel:0.28.0 with rules_nodejs 0.33.1.

First time we noticed the issue was with bazel 0.27 and rules_nodejs 0.32.

**Rules version (SHA):**

<pre>
  <code>
3b0116a8a91a75678a57ba676c246ac0fa9c90dc3d46daef305b11b54ed4467e
  </code>
</pre>

**Comment by alexeagle** [comment]
#948 is a dupe and has more debugging info
