### ISSUE TITLE
Flake in e2e test karma_typescript

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#944]
Here for future reference. I've only seen this once running locally on OSX.

```
Running e2e test karma_typescript
checking deps: release
all deps built
+ yarn test
yarn run v1.16.0
warning package.json: No license field
$ bazel test ...
Starting local Bazel server and connecting to it...
DEBUG: /private/var/tmp/_bazel_greg/048a16ebf77b9527cde85d96a4fa6bbf/external/build_bazel_rules_nodejs/internal/jasmine_node_test/jasmine_node_test.bzl:45:5: 
        WARNING: @build_bazel_rules_nodejs will no longer provide jasmine_node_test at a later release
        Instead, add a devDependency on @bazel/jasmine
        and change the load statement to
        load("@npm_bazel_jasmine//:index.bzl", "jasmine_node_test")
        
INFO: Analyzed 8 targets (299 packages loaded, 7328 targets configured).
INFO: Found 5 targets and 3 test targets...
ERROR: /Users/greg/google/rules_nodejs/e2e/karma_typescript/BUILD.bazel:19:1: Compiling TypeScript (devmode) //:lib failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at /private/var/tmp/_bazel_greg/048a16ebf77b9527cde85d96a4fa6bbf/bazel-workers/worker-1-TypeScriptCompile.log ---8<---8<---
Error: @npm//@bazel/typescript/bin:tsc_wrapped_bin cannot find module '../tsc_wrapped/perf_trace' required by '/private/var/tmp/_bazel_greg/048a16ebf77b9527cde85d96a4fa6bbf/execroot/e2e_karma_typescript/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.runfiles/npm/node_modules/@bazel/typescript/internal/tsetse/runner.js'
  looked in:
    built-in, relative, absolute, nested node_modules - Error: Cannot find module '../tsc_wrapped/perf_trace'
    runfiles - Error: Cannot find module '/private/var/tmp/_bazel_greg/048a16ebf77b9527cde85d96a4fa6bbf/execroot/e2e_karma_typescript/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped/perf_trace'
    npm/node_modules - Error: Cannot find module '/private/var/tmp/_bazel_greg/048a16ebf77b9527cde85d96a4fa6bbf/execroot/e2e_karma_typescript/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.runfiles/npm/tsc_wrapped/perf_trace'
    node_modules attribute (npm/node_modules) - Error: Cannot find module '/private/var/tmp/_bazel_greg/048a16ebf77b9527cde85d96a4fa6bbf/execroot/e2e_karma_typescript/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.runfiles/npm/tsc_wrapped/perf_trace'

    at Function.module.constructor._resolveFilename (/private/var/tmp/_bazel_greg/048a16ebf77b9527cde85d96a4fa6bbf/execroot/e2e_karma_typescript/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped_bin_loader.js:472:17)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /private/var/tmp/_bazel_greg/048a16ebf77b9527cde85d96a4fa6bbf/execroot/e2e_karma_typescript/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.runfiles/npm/node_modules/@bazel/typescript/internal/tsetse/runner.js:15:23
    at /private/var/tmp/_bazel_greg/048a16ebf77b9527cde85d96a4fa6bbf/execroot/e2e_karma_typescript/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.runfiles/npm/node_modules/@bazel/typescript/internal/tsetse/runner.js:6:17
    at Object.<anonymous> (/private/var/tmp/_bazel_greg/048a16ebf77b9527cde85d96a4fa6bbf/execroot/e2e_karma_typescript/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.runfiles/npm/node_modules/@bazel/typescript/internal/tsetse/runner.js:12:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
---8<---8<--- End of log ---8<---8<---
INFO: Elapsed time: 34.913s, Critical Path: 1.33s
INFO: 7 processes: 6 darwin-sandbox, 1 worker.
FAILED: Build did NOT complete successfully
//:testing_chromium-local                                             NO STATUS
//:testing_firefox-local                                              NO STATUS
//:user_files_test                                                    NO STATUS

FAILED: Build did NOT complete successfully
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by gregmagolan** [comment]
Moved to https://github.com/bazelbuild/rules_nodejs/issues/1223
